### ISSUE TITLE
Missing version info

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#730] opened 2018-11-12 23:21 UTC
According to the Args class, I believe this was introduced in 17763, but that's not called out here or on the main FrameworkElement page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402a8d93-4389-4fbb-fbb5-c458e4c81e1b
* Version Independent ID: 2ef5b786-cb52-4bd5-1172-780ab2b6a8b9
* Content: [FrameworkElement.EffectiveViewportChanged Event (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.effectiveviewportchanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.frameworkelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.frameworkelement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment] 2018-11-15 18:16
@michael-hawker,
The auto-generated requirements block that indicates the required SDK version is currently missing from Event pages. We are working to correct this.
This event requires [SDK 17763](https://developer.microsoft.com/windows/downloads/windows-10-sdk).
**Device family: Windows 10, version 1809 (introduced v10.0.17763.0)** 
**API contract: Windows.Foundation.UniversalApiContract (introduced v7)**

**Comment by jevansaks** [comment] 2019-04-17 17:20
Version info is now present on these pages.

**Comment by DocBrown101** [comment] 2019-11-07 12:46
Now it's missing again!

**Comment by Karl-Bridge-Microsoft** [comment] 2020-02-19 22:27
@jevansaks - if i understand this issue correctly, it looks like the info is back on the page. Can you confirm?

**Comment by DocBrown101** [comment] 2020-02-20 06:33
Yes, I can confirm that.

**Comment by Karl-Bridge-Microsoft** [comment] 2020-02-20 17:28
thanks @DocBrown101. 

@michael-hawker - closing as resolved.

**Closed as completed by Karl-Bridge-Microsoft** 2020-02-20 17:28 UTC
Labels: eng-triaged, doc-bug, docs-experience, uwp/prod
