### ISSUE TITLE
Auto claim in range Bluetooth barcode scanner

### ISSUE THREAD

**Issue by JasperE84** [MicrosoftDocs/winrt-api#922] opened 2019-02-15 21:13 UTC
I haven't found any reliable method or event to automatically detect when a Bluetooth scanner is in range and 'ready to be claimed'. (For instance after going out/in of reach or after turning on or power cycling the Bluetooth scanner device.)

What would be the right strategy here?

Please see this thread for more info:
https://stackoverflow.com/questions/54279309/autoclaim-pos-bluetooth-barcode-scanner-when-in-reach

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: dc23bb7c-4938-1ed9-7673-6768f169faf7
* Version Independent ID: a51fa0fa-b62e-39a7-364c-1fff7af60551
* Content: [BarcodeScanner.ClaimScannerAsync Method (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/nl-nl/uwp/api/windows.devices.pointofservice.barcodescanner.claimscannerasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescanner.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescanner.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment] 2019-10-22 01:34
Hi, @JasperE84, thanks for filing this issue.

It looks like the feature team has responded to your StackOverflow thread, so it's probably best to keep prompting for a response there. I wouldn't recommend beginning a duplicate support thread about this, since it'll likely end up being routed to the same feature team. However, if you do want to do that, then here's further info. 

This feels not so much like feedback specifically about the documentation, but rather like a question about the product. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:59
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:59 UTC
