### ISSUE TITLE
 BluetoothAdapter.GetRadioAsync  does not work for Desktop

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/winrt-api#340] opened 2018-05-03 06:39 UTC
I got exception `HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)`. Please, document it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b85300c4-72d7-14e1-7aed-fd7ba70ef075
* Version Independent ID: 246422b6-3dab-32d0-4ad3-0d0c33d1a494
* Content: [BluetoothAdapter.GetRadioAsync Method (Windows.Devices.Bluetooth) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothadapter.getradioasync#Windows_Devices_Bluetooth_BluetoothAdapter_GetRadioAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothadapter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothadapter.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jkumeboshi** [comment] 2018-10-09 08:46
Same for me: calling GetRadioAsync() from a desktop application returns 
HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)

**Comment by btframework** [comment] 2018-10-30 11:33
It works. Your application must be same bits as OS. For 64bit OS your application must be 64 bit. For 32 bit OS your application must be 32 bit. In case of running 32 bit application on 64 bit OS the method fails.

**Comment by xmedeko** [comment] 2018-10-30 18:35
Well, maybe it works as @btframework has written. This this is a doc request, so the behaviour should be documented if the method does not work for all configurations.
And, it would be nice to document some workaround how to make it run for 32-bit app on 64-bit OS if such workaround exists.

**Comment by btframework** [comment] 2018-10-30 18:55
Let me explaing why it requires os bits compatibility. There is something know as RadioMediaManager. It is actually COM object that provides few interfaces to manager radios (WiFi, Bluetooth, GPS, GPRS/3G and possible others). Each one has own DLL that implements the Radio Manager COM object. For Bluetooth it is BthRadioMedia.dll. And the problem that there is only one instance of that DLL compiled for the specific OS (32 or 64). No second DLL that can be used from 32 bit process on 64 bit OS. However, you can call directly to this COM obejct without WinRT API. But you may need stub application that will marshal calls from your 32 bit process to this 64 bit COM object.

**Comment by xmedeko** [comment] 2018-10-30 19:45
@btframework very well explained, thanks.
But I repeat, this is doc request, this explanation should be in the main article, not GitHub issue debate. There are more of such call in the `Windows.Devices` namespace. It should be simple to document main principle once and then mention it from all similar methods in the doc.

**Comment by stevewhims** [comment] 2019-10-24 01:01
Hi, @xmedeko. Thanks for filing this issue, and my apologies for the delay in responding.

I've published an update to the **Remarks** section of this topic to reflect the architecture limitation. I'll go ahead and close this issue now.

Thanks again!
Steve

**Closed as completed by stevewhims** 2019-10-24 01:01 UTC

**Comment by xmedeko** [comment] 2019-10-24 07:48
@stevewhims Thanks. IMO is would be useful to have technical details explained, as @btframework has written. Together with a hint how to solve it ("you may need stub application that will marshal calls from your 32 bit process to this 64 bit COM object").
Because this problem is in more Desktop - WinRt calls, then you may document it just once and link it from doc to particular methods.

**Comment by stevewhims** [comment] 2019-10-24 21:57
@xmedeko, good idea. On the technical rationale, and workaround, I'll seek input from the feature team. If/when I get that info, I'll document it (in one place, with links, as you say).

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-10-25 16:53
**UPDATE**: After input from the feature team (and confirmation that this *is* a known limitation), I updated the wording in the Remarks section. But we don't have any workaround guidance to publish at this time. ~Steve

**Comment by btframework** [comment] 2019-10-25 17:07
> **UPDATE**: After input from the feature team (and confirmation that this _is_ a known limitation), I updated the wording in the Remarks section. But we don't have any workaround guidance to publish at this time. ~Steve

Why don't simple publis IOCTL  code that switches radio on/off?

**Comment by stevewhims** [comment] 2019-10-29 03:35
Hi, @btframework. It might be worth your suggesting that idea as product feedback, since I can't action it by making changes to the documentation.

To leave product feedback, or to ask a question about the product, you can visit a topic and click **Send feedback about** \> **This product**. You'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

-Steve
