### ISSUE TITLE
[bug]SubscribedClientsChanged，this callback function in Some Win10 Device did not work,for help

### ISSUE THREAD

**Issue by ShiverZm** [MicrosoftDocs/winrt-api#1961] opened 2021-03-11 03:43 UTC
[在此处输入反馈]
[bug]SubscribedClientsChanged，this callback function in Some Win10 Device did not work,for help
but i use c# uwp it can work well, i dont know why

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b2b538d1-3288-1784-c8b0-f04989c2c1ea
* Version Independent ID: 54774b5b-a1ec-d852-f51d-4f73f2c61579
* Content: [GattLocalCharacteristic.SubscribedClientsChanged Event (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattlocalcharacteristic.subscribedclientschanged?view=winrt-17134)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattLocalCharacteristic.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattLocalCharacteristic.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2021-03-12 04:12
Hi, @ShiverZm, and thanks for filing this issue. This doesn't sound like something I can help with by changing the information in this topic.

The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions (or requests for help) regarding a support-related matter, like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2021-03-12 04:12 UTC
Labels: winrt-reference/tech, uwp/prod
