### ISSUE TITLE
InvalidArgumentException for a function with no arguments?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1730] opened 2020-07-17 16:05 UTC
The InvalidArgumentException is listed under Exeptions, but the function has no arguments. The recomendation to request new inputs from the user make no sense. The description appears to be copied from https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.getasync or some other page. If so, it is possible the entire list is not accurate for the AttachAsync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfbf6f6a-e8a1-1683-f9fc-93054c911c6b
* Version Independent ID: f8466491-c957-a6dd-baca-bf45df1cd4e7
* Content: [DownloadOperation.AttachAsync Method (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.downloadoperation.attachasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.BackgroundTransfer/DownloadOperation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.BackgroundTransfer/DownloadOperation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-07-18 00:07
Hi, @avakhrushev, and thanks for filing this issue. I don't have the info to answer this question, so I've notified the feature team (product group) about this issue, and sent them a link to it. In the meantime, be aware of these links in case you want to make use of them.

<DEVELOPER SUPPORT RESOURCES>

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

-Steve

**Comment by PeterSmithRedmond** [comment] 2020-07-18 00:42
One potential reason for an invalid argument is if the object itself is in an invalid state.

**Comment by avakhrushev** [comment] 2020-07-21 14:57
That would go against the purpose of InvalidArgumentException. What is invalid about the object's state? Perhaps there is a kind that is more suitable/descriptive for the actual failure.

**Comment by stevewhims** [comment] 2020-09-01 21:43
Hi, @avakhrushev, it feels like the documentation doesn't need to be changed here, since it's correctly documenting the behavior. For a request to change the behavior, I'd refer you to one of the developer support resources I listed earlier. I'll go ahead and close this doc issue now.

Thanks again!
Steve

**Closed as completed by stevewhims** 2020-09-01 21:43 UTC
Labels: doc-bug, winrt-reference/tech, uwp/prod, Pri2

**Comment by avakhrushev** [comment] 2020-09-02 07:36
@stevewhims but is there actually an InvalidArgumentException thrown by this method? At no point it was made clear. Would "requesting new input" from the user actually do anything, do what in what way? I am not sure what you mean by "correctly documenting", to the supposed source of information about the API that raises questions and does not answer them.

**Comment by stevewhims** [comment] 2020-09-02 19:05
Thanks, @avakhrushev, what I'll do is I'll send a mail to the feature team to double-check that this topic is correctly listing the exceptions that can be thrown by this API. Given that Peter already visited this issue and saw it, and the topic, that makes me 99% sure that the topic is correct, but I'll send the email internally just in case. I'll be happy to fix the topic if the team says it's not correct.

Thanks again!
Steve
