### ISSUE TITLE
Shift Button getting stuck on

### ISSUE THREAD

**Issue by TheJimmyJ57** [MicrosoftDocs/winrt-api#1132] opened 2019-06-18 16:34 UTC
While using `Windows.UI.Input.Preview.Injection` to simulate key presses in a program, the following code was used:
`
            InputInjector inputInjector = InputInjector.TryCreate();
            var info = new InjectedInputKeyboardInfo();
            info.VirtualKey = (ushort)(VirtualKey.Shift);
            inputInjector.InjectKeyboardInput(new[] { info });
`
When this code is used the shift get is then left stuck on for the entire PC system making it impossible for the computer to function properly as SHIFT+Click selects everything, etc.
Other simulated keys work without this "stuck" issue. Only fix so far is to restart the computer.

**Comment by ginami** [comment] 2019-06-19 23:21
Hi @thejimmyj57 -- I'm closing this issue as it seems to be a duplicate of #1133 . Thanks!

**Closed as completed by ginami** 2019-06-19 23:21 UTC
Labels: product-question
