### ISSUE TITLE
Problem with sending SysEx messages

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#538] opened 2018-08-10 21:17 UTC
Sending SysEx messages will lock up the drivers of some popular MIDI devices, causing the application to hang.
It's worth pointing out that there are currently two crippling problems with MIDI in UWP.
Both problems are discussed in the thread [WinRT MIDI stack name handling flaw. WinRT MIDI stack is presently unusable.](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/e956555c-0640-4531-9beb-cba48a847020/winrt-midi-stack-name-handling-flaw-winrt-midi-stack-is-presently-unusable)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91b829dc-d2f4-ac94-3bb0-6cfd098193c8
* Version Independent ID: ccd7e3d1-4048-aff5-549b-55d1091df0cd
* Content: [IMidiOutPort.SendMessage(IMidiMessage) Method (Windows.Devices.Midi) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi.imidioutport.sendmessage)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.imidioutport.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.imidioutport.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by EddieLotter** [comment] 2018-11-18 21:52
It appears that update 1809 fixes these issues.
Can anyone confirm?

**Comment by drewbatgit** [comment] 2020-07-24 18:25
Issues in this repo are intended specifically for fixes to the documentation, not for reporting or tracking product bugs or developer support requests. As this discussion seems related to technical issues in the product, I am going to close the issue to get it out of the documentation queue. If there is a resolution/workaround to this issue that you think should be included in the documentation, feel free to comment here, even though the status of the issue is "Closed". Thanks!

**Closed as completed by drewbatgit** 2020-07-24 18:25 UTC
Labels: product-feedback, windows/prod, Pri2
