### ISSUE TITLE
DataReader.Close()

### ISSUE THREAD

**Issue by lawabider** [MicrosoftDocs/winrt-api#1908] opened 2020-12-15 18:48 UTC
In visual studio (c++/winrt) I can't see that this method exists. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18a2770-710e-6910-6f97-357c069bf8b2
* Version Independent ID: 708e3341-3936-f0c9-a9b5-0e2b1827ad89
* Content: [DataReader.Close Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader.close?view=winrt-19041#Windows_Storage_Streams_DataReader_Close)
* Content Source: [winrt-api-build/xml/Windows.Storage.Streams/DataReader.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Streams/DataReader.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by jaigak** [comment] 2021-04-14 04:36
You don't need to call Close in C++/WinRT as the wrapping destructor will automatically call Close for you

**Comment by stevewhims** [comment] 2024-03-20 22:24
Hi, and thanks for filing this issue (and apologies for the long delay in responding to it). The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, you'd use this channel if the documentation itself is incorrect or incomplete.

But for feedback or questions about Visual Studio (or about any other product/feature/APIs), like this, you can click **Submit and view feedback for** \> **This product** (instead of **This page**), and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2024-03-20 22:24 UTC
Labels: doc-bug, winrt-reference/tech, uwp/prod, Pri2
