### ISSUE TITLE
Calling from command line application.

### ISSUE THREAD

**Issue by kinyoklion** [MicrosoftDocs/winrt-api#882] opened 2019-01-23 21:53 UTC
Is it possible that this method requires invocation from a UI thread for potential granting of permissions? (Regardless I seem to be able to find no working example of this method. Which is unfortunate given GetRadiosAsync is not suitable for most applications due to its architecture limitations).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e2886f-9b61-36c1-680b-355e023605ab
* Version Independent ID: 3a8490d0-0626-c653-8e8d-1ddf65dda11b
* Content: [Radio.FromIdAsync(String) Method (Windows.Devices.Radios) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio.fromidasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment] 2019-10-22 01:06
Hi, @kinyoklion. Thanks for filing this issue, and my apologies for the very long delay in responding.

I took a brief look through source code looking for the implementation, but I couldn't find anything that'd answer your question. It might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:58
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:58 UTC
Labels: product-question
