### ISSUE TITLE
BluetoothDevice.Name api sending wrong name

### ISSUE THREAD

**Issue by Md-OmarFaruque** [MicrosoftDocs/winrt-api#2318] opened 2023-01-04 05:31 UTC
[Enter feedback here]

To get buds device we used following api.
BluetoothDevice budsDevice = await BluetoothDevice.FromIdAsync(deviceToConnectId);

Buds display name comes from BluetoothDevice.Name Property

Sometimes api sending wrong device name.

Device name come **Bluetooth f0:cd:31:ba:8d:f2** instead of Galaxy Buds2 Pro

<HTML><HEAD><META content="IE=11.0000" http-equiv="X-UA-Compatible">
<TITLE>[PLM] P221222-04261-Problem Resolution</TITLE>	    <LINK href="/wl/ui2013/css/plm.css" rel="stylesheet" type="text/css">  
<SCRIPT src="/wl/js/com/shared/Message_en.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT type="text/javascript">
	var langType='en';
	// 서버 Division Code 추가 jongsue.hong 2014.03.02
	var serverDivisionCode = '25';
	var contextPath='/wl';
	
	  
	  
	  
	  
	  	
	var channelURI='splm.sec.samsung.net:80/wl';
	var hostUrl='splm.sec.samsung.net:80';
	var rootPath = contextPath;
	var pbomUrl ='http://splm.sec.samsung.net:8510';
	
	

	var cacheVersion = '?ver=1211_073531';
	var rh = '8e89cf23ccf4e544e22595440822db12247c73e349188801950f57512a54da56';

	
	var userTypeCode = '';
</SCRIPT>
 
<SCRIPT src="/wl/js/com/shared2013/jquery-1.9.0.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared2013/jquery-migrate-1.1.1.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared2013/jquery-ui-1.10.2.custom.min.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared2013/commonUtil.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared2013/plm.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared2013/jsrender.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared/collection.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/shared/checkJob.js?ver=1211_073531" type="text/javascript"></SCRIPT>
					
<SCRIPT src="/wl/js/com/shared2013/require.js?ver=1211_073531" type="text/javascript"></SCRIPT>
 
<SCRIPT src="/wl/js/com/webeditor/cafe/2.3.21.1/cafe_2.3.21.1.min.js" type="text/javascript" charset="UTF-8"></SCRIPT>
 
<SCRIPT type="text/javascript">

ComSharedLoading.hideLayoutLoadingBar();

function getLocale() {return "en";}
</SCRIPT>
 
<SCRIPT type="text/javascript"></SCRIPT>

<SCRIPT language="JavaScript">
function fswExcept(bExcept)	{}
</SCRIPT>
<LINK href="/wl/js/com/webeditor/cafe/2.3.21.1/skins/default-base/all.min.css" rel="stylesheet" type="text/css">
<STYLE> #fontInstalledTest, #fontTestBed { position: absolute; left: -9999px; top: 0; visibility: hidden; } #fontInstalledTest { font-size: 50px!important; font-family: "Comic Sans MS";}</STYLE>

<STYLE id="fonttestStyle"> #fonttest3 { font-size: 50px!important; font-family: SimSun, "Comic Sans MS"; } </STYLE>

<SCRIPT src="/wl/js/com/calendar/jquery-private.js?ver=1211_073531" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery-private"></SCRIPT>

<SCRIPT src="/wl/js/com/calendar/moment.js?ver=1211_073531" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="moment"></SCRIPT>

<SCRIPT src="/wl/js/com/shared2013/jquery-1.9.0.js?ver=1211_073531" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery"></SCRIPT>

<SCRIPT src="/wl/js/com/shared2013/jquery-migrate-1.1.1.js?ver=1211_073531" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery-migrate"></SCRIPT>

<SCRIPT src="/wl/js/com/shared2013/jsrender.js?ver=1211_073531" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jsrender"></SCRIPT>
</HEAD><BODY style="-ms-zoom: 1;"><FORM name="defectSolForm" method="post" target="_self" autocomplete="off"><DIV class="popScrollContainer"><DIV id="content"><DIV class="dataGrid nolist mgT-1"><TABLE><TBODY><TR id="trHistory"><TD colspan="2"><UL class="mentTxt mgL0" id="commentListUl"><LI id="mainArea" style="position: static;" display_type="COMMENT" history_type="" comment_type="C"><DIV class="preWrapScrollX" commentid="01DG7KX9JtPMWL1000"><DIV id="cafe-note-contents" style='line-height: 1.2; font-family: "굴림",Gulim,Arial; font-size: 9pt;'><P><STRONG>승룡's Buds2 Pro</STRONG> </P></DIV></DIV></LI></UL></TD></TR></TBODY></TABLE></DIV></DIV></DIV></FORM></BODY></HTML>
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 190b7ea9-52bb-bb6d-2afb-430a9f77e49a
* Version Independent ID: 5d1f0a31-1305-023f-ff09-a6d3d951ba39
* Content: [BluetoothDevice.Name Property (Windows.Devices.Bluetooth) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothdevice.name?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2023-01-18 00:35
Hi, @engfaruque, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For reporting bugs in the product (or questions, or requests for help) regarding a specific scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2023-01-18 00:35 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
