### ISSUE TITLE
UWP + SSL/TLS in StreamSocketListener or TcpListener

### ISSUE THREAD

**Issue by MultiCoinCharts** [MicrosoftDocs/winrt-api#1594] opened 2020-04-07 05:54 UTC
Both classes aren't capable in broadcasting plain IPs over SSL. Is there an undocumented work around or IP abstraction solution example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad22c106-fd40-9974-3ae0-9ea6912fc308
* Version Independent ID: 83db1fee-6b9a-5de9-9abc-e80b1c1c9593
* Content: [StreamSocketListener Class (Windows.Networking.Sockets) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Sockets.StreamSocketListener#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.sockets.streamsocketlistener.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.sockets.streamsocketlistener.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-04-07 21:44
Hi, @P-Medicado, this feels like a question, or feedback, about the product itself rather than about the documentation. Is that correct?

For questions/feedback about the product, you can visit a topic and click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

-Steve

**Comment by MultiCoinCharts** [comment] 2020-04-07 22:07
You're right, it isn't undocumented, but the later release of the UWP framework actually do support broadcasting over a plain IP. That could mean so much for UWP devs - LAN games, LAN Media Servers, WebSockets, all things that need SSL to work on modern browsers. I don't know which release added SSLStream class to UWP. It might be helpful to document this is possible! This doesn't require priority.

**Comment by stevewhims** [comment] 2020-04-07 22:16
Thanks, @P-Medicado, I'll chat with my product team contact and see what we can do.

-Steve

**Comment by stevewhims** [comment] 2020-04-07 23:09
Hi, @P-Medicado, just an update on this after conferring with the product team. The feeling is that the current level of info here is fine, and we're not seeing anything that we feel is compelling to add.

Just by way of context, the StreamSocketListener is the Windows Runtime class; and TcpListener is the .NET class. For StreamSocketListener, we don’t support the 'server' side of TLS/SSL; that's a known limitation. For TcpListener, as you mentioned, you can use System.Net SslStream. According to the [.NET Networking APIs for UWP Apps](https://devblogs.microsoft.com/dotnet/net-networking-apis-for-uwp-apps/) blog post, that's been part of Windows Runtime programming for a while now.

**Comment by MultiCoinCharts** [comment] 2020-04-07 23:28
Thank you for getting so much info, @stevewhims. I understand moreso now, when I visit [System.Net.Security.SslStream](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream) then select Version: UWP. It falls back to .NET Framework 4.8, it adds an error message: 
> "The requested page is not available for UWP 10.0. You have been redirected to the newest product version this page is available for."  
  
What is the correct URL for SslStream for UWP?

**Comment by stevewhims** [comment] 2020-04-08 00:15
Hi, @P-Medicado. As far as I know, that *is* the correct URL for **System.Net.Security.SslStream** for use within a UWP app. That's the *only* topic that exists for **System.Net.Security.SslStream**.

If you create a new C# UWP project in Visual Studio and begin to use the **System.Net.Security.SslStream** type, then you'll see that its metadata comes from `microsoft.netcore.universalwindowsplatform\6.2.9\ref\uap10.0.15138\System.Net.Security.dll`. Which is strong evidence that it *is* a valid .NET type for use within UWP apps.

It's possible that the tagging/filtering system for the [.NET API browser](https://docs.microsoft.com/dotnet/api) isn't correct for that type.

But I'm unable to take any feedback around the design of the .NET API browser or documentation here, since this is the documentation for Windows APIs. My team doesn't own the .NET API content, nor the .NET API browser.

Thanks!
Steve

**Comment by MultiCoinCharts** [comment] 2020-04-08 00:18
You are awesome, truly; thank you entirely for directing me so thoroughly. I absolutely appreciate all this

**Comment by stevewhims** [comment] 2020-04-08 00:59
Great, you're welcome, @P-Medicado! I'll go ahead and close this issue now.

Thanks again!
Steve

**Closed as completed by stevewhims** 2020-04-08 00:59 UTC
Labels: product-question, winrt-reference/tech, uwp/prod
