### ISSUE TITLE
What is the value of the BytesReceived ?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1727] opened 2020-07-17 08:02 UTC
It is "total number of bytes received", but it also "may be smaller". By how much? Wouldn't _total_ be larger?
Why bring up headers, in the context of data download progress? The TotalBytesToReceive page does not. Now I have to wonder if it is an important detail that was left out by mistake.

If it means to say it reflects the number of bytes received of the TotalBytesToReceive, including after the download is restarted, there is probably a more concise way to phrase that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cdfbcc-42f1-e2d2-cf29-95e60a21f178
* Version Independent ID: e277ad8e-694a-0c99-4d4e-23c83cfb9210
* Content: [BackgroundDownloadProgress.BytesReceived Field (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgrounddownloadprogress.bytesreceived?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.BackgroundTransfer/BackgroundDownloadProgress.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.BackgroundTransfer/BackgroundDownloadProgress.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-07-18 00:07
Hi, @avakhrushev, and thanks for filing this issue. Our SME has updated the topic with the following description: "The total number of data bytes received. This value does not include bytes received as response headers. Download operations can be restarted (for example, after a network outage). When operations are restarted, they might have to discard previously downloaded bytes and therefore the number of bytes downloaded might not always increase from one report to the next."

Also, just FYI, here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

-Steve

**Comment by avakhrushev** [comment] 2020-07-24 11:12
Thank you, I am still unsure about it being called "total" though.
It doesn't sum up the bytes from prevous attempts, it does not include headers - what's "total" about it? It is total - of what parts? Can't help but wonder if there are some relevant facts omitted when I read it this way.

**Comment by stevewhims** [comment] 2020-08-04 22:04
Hi, @avakhrushev, I'll go ahead and close the issue since our SME has updated it as seemed appropriate. However, I will also ping them just to let them know of your follow-up comments.

Thanks!
Steve

**Closed as completed by stevewhims** 2020-08-04 22:04 UTC
Labels: doc-bug, winrt-reference/tech, uwp/prod, Pri2
