### ISSUE TITLE
UWP:- GraphicsCaptureAccess.RequestAccessAsync(GraphicsCaptureAccessKind.Borderless) throws exception

### ISSUE THREAD

**Issue by KarthikRichie** [MicrosoftDocs/winrt-api#2126] opened 2021-12-01 06:39 UTC
I'm trying to have a borderless screen capture by updating by project target version to windows 10 SDK 20348. I updated the package manifest to include graphicsCaptureWithoutBorder capability like below,

```
<Package   xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"   xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"   xmlns:uap6="http://schemas.microsoft.com/appx/manifest/uap/windows10/6" xmlns:uap11="http://schemas.microsoft.com/appx/manifest/uap/windows10/11" IgnorableNamespaces="uap mp uap6 uap11">    
      <Capabilities>
        <Capability Name="internetClient" />
        <uap6:Capability Name="graphicsCapture"/>
        <uap11:Capability Name="graphicsCaptureWithoutBorder"/>    
     </Capabilities> 
</Package>

```
and adding the following code to request consent to disable border,

```
Direct3D11CaptureFramePool _framePool = Direct3D11CaptureFramePool.CreateFreeThreaded(
                    _canvasDevice, // D3DDevice
                    DirectXPixelFormat.B8G8R8A8UIntNormalized,
                    2, 
                    _captureItem.Size);
           GraphicCaptureSession _session = _framePool.CreateCaptureSession(_captureItem);
            AppCapabilityAccessStatus appCapabilityAccessStatus = await GraphicsCaptureAccess.RequestAccessAsync(GraphicsCaptureAccessKind.Borderless);
            if (appCapabilityAccessStatus == AppCapabilityAccessStatus.Allowed)
            {
                _session.IsBorderRequired = false;
            }
```

However, upon invoking RequestAccessAsync method, the following exception (in the attached image occurs),

![image](https://user-images.githubusercontent.com/33217928/144184613-72168719-9482-4dea-895b-1a5c8c47b122.png)

I'm I missing something here?

**Comment by stevewhims** [comment] 2021-12-02 02:53
Hi, @KarthikRichie, and thanks for filing this issue. Is there a specific code example in a specific topic that is incorrect?

If so then if you visit that topic you can then (**Send feedback about** \> **This page**). That channel is for feedback about the documentation in that topic; for example, if the content is incorrect or incomplete.

For questions (or requests for help) regarding a specific scenario or issue, like this, one option is to visit and topic and click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no specific action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2021-12-02 02:53 UTC
Labels: Pri3
