### ISSUE TITLE
Multiple WriteValueAsync() results in stuttering data transmission

### ISSUE THREAD

**Issue by ChriDit** [MicrosoftDocs/winrt-api#2423] opened 2023-11-15 06:22 UTC
I use WriteValueAsync() to write data without response to an BLE device.

Therefor 

`gattCharacteristic.WriteValueAsync(dataWriter.DetachBuffer(), GattWriteOption.WriteWithoutResponse))`

is called ~200 times in ~1 seconds to write data as fast as possible.

On receiving BLE device I can see now ~2-5 write-without-response messages arriving in a "block" with nearly no time delay between them, then I see a break without new receives with a length of  ~1-2 seconds before next "message-block" is received. 
So data, which was written in ~1s, takes up to 90 seconds to arrive completely on BLE device (probably buffered from Windows).

Does anyone has an idea, why breaks are there and how to get rid of them?

Using a smartphone app, which does the same data transfer with write-without-response messages to same BLE device, transfers data much more quickly than Windows does.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 90524148-a1cb-13ad-922b-7557f64abc00
* Version Independent ID: 05adef7b-05c2-ad83-f476-ae7f4970b57b
* Content: [GattCharacteristic.WriteValueAsync Methode (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://learn.microsoft.com/de-de/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristic.writevalueasync?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattCharacteristic.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattCharacteristic.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2023-11-15 17:40
Hi, @ChriDit, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

But this particular issue doesn't feel like it's saying that something needs changing in the docs.

For questions (or requests for help) regarding a specific scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2023-11-15 17:40 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
