### ISSUE TITLE
WebView shake when page navigated

### ISSUE THREAD

**Issue by AceLearnGit** [MicrosoftDocs/winrt-api#985] opened 2019-03-20 06:55 UTC
I use webview in a page, when i navigate  from this page or navigagte to this page, the webview(or the content in webview) shaked, it makes user very uncomfortable, and i found no idea from document why webview shaked when page navigation fired

**Comment by ginami** [comment] 2019-03-21 22:42
Hi @AceLearnGit -- can you give me the URL for the doc where you expected to find this information? This will help me route your question to the correct author. Thank you!

**Comment by AceLearnGit** [comment] 2019-03-22 15:26
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview
This the doc of webview. I  find api of webview there.
When navigate to or from page  that contains webview ctrl ,the content in webview shaked
I think it’s a bug of webview, so i want somebody of microsoft fix it.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Gina P. <notifications@github.com>
发送时间: Friday, March 22, 2019 6:42:49 AM
收件人: MicrosoftDocs/winrt-api
抄送: AceLearnGit; Mention
主题: Re: [MicrosoftDocs/winrt-api] WebView shake when page navigated (#985)


Hi @AceLearnGit<https://github.com/AceLearnGit> -- can you give me the URL for the doc where you expected to find this information? This will help me route your question to the correct author. Thank you!

―

**Comment by jevansaks** [comment] 2019-03-22 18:14
Do you have a repro app that we could try? Is there a video of the "shake" that we could look at? It's not clear from the description what the problem is.

**Comment by AceLearnGit** [comment] 2019-04-03 15:33
Sorry reply late, just see this video, shows webview ctrl in Xaml Control Gallery develpoed by ms, when I click other menu to navigate to other pages , the webview shaked. In my video ,7-8s and 11-12s shows the problem.
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jevan Saks <notifications@github.com>
发送时间: Saturday, March 23, 2019 2:14:28 AM
收件人: MicrosoftDocs/winrt-api
抄送: AceLearnGit; Mention
主题: Re: [MicrosoftDocs/winrt-api] WebView shake when page navigated (#985)


Do you have a repro app that we could try? Is there a video of the "shake" that we could look at? It's not clear from the description what the problem is.

―

**Comment by jevansaks** [comment] 2019-04-03 17:13
@acelearngit I think you tried to attach the file to your email but that didn't get attached to the github issue. Please go to https://github.com/MicrosoftDocs/winrt-api/issues/985 to continue the discussion and attach your file there. Thanks!

**Comment by AceLearnGit** [comment] 2019-04-04 15:14
Here is the video
[webviewbug.zip](https://github.com/MicrosoftDocs/winrt-api/files/3044158/webviewbug.zip)

**Comment by jevansaks** [comment] 2019-04-19 18:17
@stmoy can you dig in to whether this is a sample bug or platform issue? If platform, please file it on the MUX github.

**Comment by stmoy** [comment] 2019-04-19 21:22
@AceLearnGit - thank you for reporting this. Are you only seeing this behavior in the Xaml Controls Gallery app, or in other apps as well?

@jevansaks - I believe the issue has to do with the "page enter" animation causing the WebView to re-render. When I disable animations at the system-level, the issue seems to go away. Not sure if that points towards a platform bug or a sample bug, but we could try disabling the animation in the sample specifically for the webview page.

**Comment by AceLearnGit** [comment] 2019-04-20 02:25
Not only Xaml Controls Gallery app, but also my app and others have this problem. And I find the page navigation animations make this problem too. So I have to disable the animation when navigate to and navigate from a webview page.

发自我的 iPhone

在 2019年4月20日，05:22，Steven Moyes <notifications@github.com<mailto:notifications@github.com>> 写道：


@AceLearnGit<https://github.com/AceLearnGit> - thank you for reporting this. Are you only seeing this behavior in the Xaml Controls Gallery app, or in other apps as well?

@jevansaks<https://github.com/jevansaks> - I believe the issue has to do with the "page enter" animation causing the WebView to re-render. When I disable animations at the system-level, the issue seems to go away. Not sure if that points towards a platform bug or a sample bug, but we could try dsabling the animation in the sample specifically for the webview page.

**Comment by stmoy** [comment] 2019-04-29 22:56
Gotcha, thanks. It sounds like we have three things to do: 
1. Update the Xaml Controls Gallery WebView sample to stop the animation
2. Add documentation to WebView guidance to suggest turning off page transitions when navigating to a page with WebView
3. Investigate why the animation and the WebView page don't play well together

**Comment by hkhmsft** [comment] 2021-01-25 23:23
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback!

**Closed as completed by hkhmsft** 2021-01-25 23:23 UTC
Labels: area-xaml, eng-triaged, doc-bug, Pri3
