### ISSUE TITLE
When will Close/Disconnect be implemented? [Windows.Devices.Bluetooth.BluetoothDevice]

### ISSUE THREAD

**Issue by MKGNZ** [MicrosoftDocs/winrt-api#849] opened 2019-01-09 16:39 UTC
When will Close/Disconnect be implemented?
Are you planning to have a disconnect? Dispose() doesn't close the connection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c006da6d-51e7-a09e-d359-ecdbbef51133
* Version Independent ID: a242f51a-c55b-43dc-12da-ed570c3ef6e4
* Content: [BluetoothDevice.Close Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothdevice.close)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothdevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothdevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment] 2019-10-22 00:58
Hi, @MKGNZ. Thanks for filing this issue, and my apologies for the very long delay in responding.

In terms of the docs, **Close** is currently documented as being available only via the C++ language projections (so, not via C#, VB, nor JavaScript). **Dispose** is available for the .NET languages, and **Dispose** typically does whatever it takes to free any unmanaged resources. It's arguable whether that should close the connection (as long as there's no leak if it doesn't), but the topic doesn’t lead us to expect it to. Also, in the docs, I can't speak to when/whether any API that's not currently implemented might be implemented.

In terms of product correctness, you could pursue this as a question about the product. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:58
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:58 UTC
