### ISSUE TITLE
There is no AccountUpdate message when user insert a SIM card with lock pin.

### ISSUE THREAD

**Issue by minjiew88** [MicrosoftDocs/winrt-api#2225] opened 2022-05-24 05:54 UTC
[Enter feedback here]
User inserts a standard SIM card without Lock Pin, AccountUpdate message is received.
User inserts a SIM card with Lock Pin, AccountUpdate message is not received.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2d5e73c-bcc0-a707-73b2-cf9a22e69ba2
* Version Independent ID: a924ae73-758e-6d50-d7bd-ba0d5d65a582
* Content: [MobileBroadbandAccountWatcher.AccountUpdated Event (Windows.Networking.NetworkOperators) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.mobilebroadbandaccountwatcher.accountupdated?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Networking.NetworkOperators/MobileBroadbandAccountWatcher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.NetworkOperators/MobileBroadbandAccountWatcher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-05-24 16:55
Hi, @minjiew88, and thanks for filing this issue.

For feedback about missing, incorrect, or incomplete info in a specific topic of documentation, you can visit that topic, and then **Send feedback about** \> **This page**.

For questions/feedback/support about the platform (Windows and its APIs) or tools, and how they behave, you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since it doesn't look like we're identifying any documentation that's wrong. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-05-24 16:55 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
