### ISSUE TITLE
Device Watcher is unstable

### ISSUE THREAD

**Issue by dungpt4** [MicrosoftDocs/winrt-api#429] opened 2018-06-25 09:45 UTC
After I start the DeviceWatcher, it can add and remove peers several times, after a while no event is invoked (added, removed, updated or enumerated). I have tried both PeerFinder.DeviceWatcher and WifiDirect.DeviceWatcher (in the situation of WifiDirect, it is even worse, no event is fired after the first enumerated). Is there any help for this? The sample of yours did not work either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ad3e67-629a-e009-41eb-1a53d7c2c354
* Version Independent ID: 28bcd359-4085-bfe8-24e4-12e61263f976
* Content: [PeerFinder.CreateWatcher Method (Windows.Networking.Proximity) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.proximity.peerfinder.createwatcher)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.proximity.peerfinder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.proximity.peerfinder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by dungpt4** [comment] 2018-06-25 09:47
I mean PeerFinder.PeerWatcher, not DeviceWatcher

**Comment by stevewhims** [comment] 2018-06-25 23:48
Thanks, @dungpt4, I'm investigating the issue! ~Steve.

**Comment by stevewhims** [comment] 2018-07-12 18:45
Thanks for raising this issue, @dungpt4, I have some info that I hope will help. WiFiDirect.DeviceWatcher will only do one scan, fire enumeration complete, and then do nothing. That is by design, as it does not attempt to continuously scan for devices. PeerWatcher is designed to start a new scan after each one is complete, but it uses random exponential backoff with 1-10 seconds of random backoff. The exact schedule is:
 
- 1-10s + 2s (10 times)
- 1-10s + 1min (4 times)
- 1-10s + 10min
 
So, if the user leaves PeerWatcher running for about 5-7 minutes or so, it will only periodically scan every 10 minutes. There is a power cost to frequent scans, so the default behavior is to back off to a very infrequent schedule, with the assumption that the user will only run the watcher for a couple of minutes at the most (e.g. on a “connect to other devices” page of an app).

**Comment by stevewhims** [comment] 2018-08-10 18:55
@dungpt4 , I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2018-08-10 18:55 UTC
