### ISSUE TITLE
Sending Midi Messages

### ISSUE THREAD

**Issue by MatsEx** [MicrosoftDocs/winrt-api#1255] opened 2019-10-06 13:39 UTC
Is there a way to broadcast/send a midi message to "all" devices? Without sending it to a predefined one?

For example, a midi keyboard doesn't have to tell to whom it sending it's midi, its up to the program (DAW) or another device to pick it up.
DAWs for example doesn't show up as a midi devices even if it can recieve MIDI messages.
DAWs also can listen to "All midi Inputs".
I am trying to remote control my daw from my app but since it doesn't show up as a device I cant find a way to send messages to it.
It's no problem if I for example use my Midi Keayboard. I can let the DAW recieve from that keyboard or just recieve from all midi, it works both ways.

Am I missing something, or can I only communicate with devices that can be found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 323778d3-4ab7-46d3-3117-3492769bd73b
* Version Independent ID: 500c30fe-261f-94d3-a143-f4d1915c7777
* Content: [Windows.Devices.Midi Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-10-07 23:41
Hi, @MatsEx, thanks for reaching out with this question. This feels not so much like feedback specifically about the documentation, but rather like a question about the product. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

Thanks!
Steve

**Closed as completed by stevewhims** 2019-10-07 23:41 UTC

**Comment by MatsEx** [comment] 2019-10-08 07:00
Ah, sorry! My mistake!
Thanks for the feedback!
