### ISSUE TITLE
The link to Dispose goes to a 404 page

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/winrt-api#871] opened 2019-01-19 00:00 UTC
https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.close includes a link to a "Dispose' method. That method doesn't actually have any documentation and IMHO doesn't need any (it's just a regular dispose call like all the other ones in .NET). There's also a link to Dispose in the TOC that also leads to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe59d5b-f1fd-b5ff-fff1-5897f30eeb78
* Version Independent ID: e9521fcf-10f3-e731-0359-676f4b5d13d3
* Content: [HttpResponseMessage.Close Method (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.close)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpresponsemessage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpresponsemessage.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by PeterSmithRedmond** [comment] 2019-01-19 00:01
Correction: the dispose link in the TOC does go to a valid page -- https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.dispose

**Comment by stevewhims** [comment] 2019-01-19 00:43
Hi, @PeterSmithRedmond, thanks for raising this issue! I'm working on a correction to that link now. I agree that there's no critical value to such a link working for folks familiar with .NET but I think in this case since the TOC links to a topic, I'll try and get this link directing to the same topic. I've just Completed a PR so once I've confirmed that's working ok I'll respond back here and then close the issue. Thanks again! ~Steve

**Comment by stevewhims** [comment] 2019-01-19 01:35
That link is working (on the review site), so this fix should be live within 24 hours (or Monday at the latest). I'll optimistically resolve (and close) this issue, but please reopen it if there are any problems. ~Steve

**Closed as completed by stevewhims** 2019-01-19 01:35 UTC
