### ISSUE TITLE
Can this work in a non-UWP context?

### ISSUE THREAD

**Issue by jakehockey10** [MicrosoftDocs/winrt-api#797] opened 2018-12-10 00:40 UTC
Hello,

I'd like to develop a nuget package that my company can use across a suite of WPF apps.  I'm having trouble understanding the compatibility limitations.  Is it possible to use this library in a non-UWP context?  If so, can someone point me to recent documentation on this subject or help me out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8f814b-ff35-aca5-3228-cebe3e842bb6
* Version Independent ID: 6f2f9630-5bd7-f1ff-4469-6f21bd898b91
* Content: [Windows.Devices.Bluetooth Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2018-12-10 19:28
Hi, @jakehockey10, have you seen this FAQ? https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-dev-faq#can-i-access-these-apis-from-win32. That FAQ links to an instructive blog post about calling Windows Runtime APIs from WPF.

If the info above shows you how to call the Windows Runtime version of the Bluetooth APIs from WPF (there's also a Win32 version of the same APIs, but we recommend using the WinRT version going forward, if you can) then, after that, it'd be a WPF question around how to package code into a reusable dll. Portable Class Libraries used to be one option there, but I suspect that more modern alternatives are likely to be the Visual Studio project templates named Class Library (.NET Standard) and Class Library (.NET Core). A WPF question such as that would be out of scope for this topic, so I'd advise pursuing that remaining question on a topic more like this kind of thing: https://docs.microsoft.com/dotnet/standard/class-libraries. 

Thanks!
~Steve

**Comment by jakehockey10** [comment] 2018-12-11 00:02
@stevewhims, thanks for the response! I did happen upon that faq. Unfortunately, when I call connect or pair methods, I get a `PlatformNotSupportedException`. I can query for nearby devices, but as soon as I call a method in `DeviceInformation` or `BluetoothLEDevice`, I get that exception. This is even when integrating straight into the WPF project instead of a standalone class library.

I can't find much on why this exception is thrown despite how much I see the community getting this to work

**Comment by stevewhims** [comment] 2018-12-11 00:14
Ok, let me ask around internally and see what I can find out. I agree, it seems prudent to remain in a WPF project until we get this working, and then move it out into a class lib. I'll get back to you if/when I get info. ~Steve

**Comment by jakehockey10** [comment] 2018-12-11 16:13
![image](https://user-images.githubusercontent.com/1821383/49813485-c5900480-fd24-11e8-838f-f473073ec426.png)
![image](https://user-images.githubusercontent.com/1821383/49813493-ccb71280-fd24-11e8-82f2-27c5347f8c37.png)
![image](https://user-images.githubusercontent.com/1821383/49813507-d17bc680-fd24-11e8-9d7a-4b0075012ac5.png)

I noticed that windows.winmd was coming from a path that included a version number similar to a windows os version number that was higher than my version of windows.  So I tried referencing the earliest version instead, but still got this issue.  `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0` `=>` `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0`

**Comment by stevewhims** [comment] 2018-12-11 22:09
Hi, @jakehockey10, I fear that I'm not going to be able to provide meaningful support here, since this per-topic feedback channel is intended for identifying and correcting documentation problems with the specific topic. If there are corrections to be made to documentation, then I strongly suspect that those changes wouldn't be made on this particular topic (rather, on some .NET or VS topic). The product team says "The APIs are supported in WPF/Console/etc, although we don't have any samples ourselves, and it's not something we typically try. I would suspect the issue here is not Bluetooth-specific, if you are hitting the same trouble with the other APIs, then you're likely missing a reference/incorrect version."

I understand that this is not an ideal response, but in terms of next steps for you, the [Windows developer feedback site](https://wpdev.uservoice.com) is the right place to file a product bug. For issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a product bug or something else. For problems/errors/omissions with the actual documentation about how to use Windows Runtime APIs work, this is the right forum to raise those. Thanks again for the feedback and for asking this question. I do regret the inconvenience. ~Steve

**Comment by jakehockey10** [comment] 2018-12-12 17:36
@stevewhims thanks for the response.  I really appreciate your time.  My team has decided to use me for other projects considering the unknowns related to this POC.  I will definitely reach out on the sites you suggested I continue this discussion on if and when I get assigned to this again.  From what I can tell, as .net core and .netstandard move forward, this will get more and more streamlined/easier to do.  But there are also other 3rd party APIs out there that talk to Low Energy Bluetooth without the UWP context limitation of the Windows 10 APIs.  

Again, thanks for your help/time spent looking into this.

**Comment by stevewhims** [comment] 2018-12-13 00:24
You're welcome, and again apologies we couldn't resolve this here and now. I'll go ahead and close this issue. Thanks! ~Steve

**Closed as completed by stevewhims** 2018-12-13 00:24 UTC
