### ISSUE TITLE
Width and Height are called PixelWidth and PixelHeight in the struct.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#480] opened 2018-07-17 16:13 UTC
PixelWidth should be changed to Width & PixelHeight should be changed to Height.

Width and Height are unambiguous in context of a Bitmap. Width and Height are also used by convention in every framework I'm familiar with such as DirectX https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/ns-d3d11-d3d11_texture2d_desc. It's unnecessary and undesirable to have Pixel prepended to these properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d1d34d-0c30-2810-1bee-f1509b590b38
* Version Independent ID: 0384b554-c858-97ba-8fc7-dad95ec15974
* Content: [SoftwareBitmap Constructor (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap.-ctor#Windows_Graphics_Imaging_SoftwareBitmap__ctor_Windows_Graphics_Imaging_BitmapPixelFormat_System_Int32_System_Int32_Windows_Graphics_Imaging_BitmapAlphaMode_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2020-07-24 21:36
Hi, @Gavin-Williams, and I'm sorry it's taken us so long to respond to this issue!

This is a feature request to change the name of an API, or of a component of an API. The feedback channel here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions or feedback about the design/naming of APIs, one option is to click **Send feedback about** \> **This product**, and you'll be taken to Microsoft Q&A (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close the issue in the light of the above.

Thanks again!
Steve

**Closed as completed by stevewhims** 2020-07-24 21:36 UTC
Labels: product-feedback, windows/prod, Pri2
