### ISSUE TITLE
Set Advertisement.Flags() will cause exception when BluetoothLEAdvertisementPublisher start.

### ISSUE THREAD

**Issue by 13xiaobang** [MicrosoftDocs/winrt-api#2272] opened 2022-08-10 03:18 UTC
[Enter feedback here]
On my windows10, run code below to do ble advertisement:

`auto publisher =  Bluetooth::Advertisement::BluetoothLEAdvertisementPublisher();

// Add custom data to the advertisement
auto manufacturerData = Bluetooth::Advertisement::BluetoothLEManufacturerData();
manufacturerData.CompanyId(0xaaaa);
auto writer = DataWriter();
writer.WriteByte('1');
writer.WriteByte('2');
writer.WriteByte('3');

manufacturerData.Data() = writer.DetachBuffer();
publisher.Advertisement().ManufacturerData().Append(manufacturerData);
publisher.UseExtendedAdvertisement(true);

publisher.Advertisement().Flags(Bluetooth::Advertisement::BluetoothLEAdvertisementFlags::GeneralDiscoverableMode); //set adv flags
printf("publisher flags :%d", publisher.Advertisement().Flags().Value()); // log shows flags was set.

publisher.Start(); //meet winrt::hresult_invalid_argument here...`

I try the code above without "set Advertisement flags" and the code can run successfully, but the ble advertisement can not be discoveried. So I think advertisement flags should be set ?  Then if flags is set ，how to deal with with the exception? If I have missed other params should be set together then cause the exception? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a585126-72e0-0dc2-d0bc-f0127e548b4e
* Version Independent ID: 57eec18b-e62f-d111-e1fe-b302b9bd318a
* Content: [BluetoothLEAdvertisement.Flags Property (Windows.Devices.Bluetooth.Advertisement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.flags?view=winrt-19041#windows-devices-bluetooth-advertisement-bluetoothleadvertisement-flags)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisement.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-08-11 00:19
Hi, @13xiaobang, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete. But as far as I know, the description of this API does correctly reflect the intent of its functionality. So we wouldn't want to change the documentation here.

For questions or feedback (or requests for help) regarding a specific coding scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-08-11 00:19 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
