### ISSUE TITLE
is a call to RegisterStreamSocketListenerAsync (or equivalent) nessecary

### ISSUE THREAD

**Issue by Cyrille-de-Brebisson** [MicrosoftDocs/winrt-api#1638] opened 2020-05-01 09:40 UTC
Hello,

I am adding dns-sd to an existing, platform independent app.
In my app, I already have a native socket that I am using for the rest of my application.
How can I advertise a dns-sd service without having to create a winRT socket?

Thanks, 
Cyrille

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8c3eba-2488-5fc4-fb87-f3f2f6fdfca3
* Version Independent ID: fbeea8e4-6b13-47c7-adca-994667231a2d
* Content: [DnssdServiceInstance Class (Windows.Networking.ServiceDiscovery.Dnssd) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd.dnssdserviceinstance?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.Networking.ServiceDiscovery.Dnssd/DnssdServiceInstance.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.ServiceDiscovery.Dnssd/DnssdServiceInstance.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-05-06 21:00
Hi, @Cyrille-de-Brebisson, and thanks for filing this issue.

I contacted the feature team to see whether, in light of this question, we needed to add more info to the docs, but the consensus is that there isn't a pressing need to add more content in this case.

For the use case of combining Windows Sockets-style programming with Windows Runtime programming, that's not an officially recommended mix, and it's not something we'd be able to give advice on since it's not possible to retrieve a Windows Sockets socket from a Windows Runtime socket, nor vice versa. With DNS-SD there's extra complexity due to the background processing, change notifications, "hydration" and "rehydration" of sockets.

So we wouldn't be able to offer support with your scenario here, nor update the docs with more info. But here are some support resources that may be of some help.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve

**Comment by Cyrille-de-Brebisson** [comment] 2020-05-07 05:43
Hello,

Thanks to the detailed answer. Even if it is an unsatisfactory one...

From various testing, I discovered that creating that socket was necessary for the system to work...
BUT, the advertizing port does NOT have to match this socket, which means that one can still use the socket port coming from the rest of the program for advertizing and connection, but that you have to create a random, unused socket for the dns-sd to work...

Cyrille

**Comment by stevewhims** [comment] 2020-06-03 01:33
Thanks for the response! I'll go ahead and close the issue now, then.

-Steve

**Closed as completed by stevewhims** 2020-06-03 01:33 UTC
Labels: product-question, winrt-reference/tech, uwp/prod, Pri2

**Comment by FredeJ** [comment] 2020-08-19 14:18
@Cyrille-de-Brebisson Any chance you can provide a sample this? I'm having a hard time making it work.
