### ISSUE TITLE
Link issues

### ISSUE THREAD

**Issue by BenWhite27** [MicrosoftDocs/winrt-api#859] opened 2019-01-13 12:48 UTC
Canvas.Left/Top/ZIndex are all 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d504d09f-0104-e46f-6135-99b147603621
* Version Independent ID: 8eee6397-da9a-839a-d25e-33ea5f60c07e
* Content: [Canvas Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.canvas)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment] 2019-04-18 17:28
Duplicate of #736

**Closed as completed by jevansaks** 2019-04-18 17:28 UTC
Labels: broken-link
