### ISSUE TITLE
Exceptions topic?

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/winrt-api#838] opened 2019-01-04 16:21 UTC
Hello - although NOT explicitly stated in the documentation, does one ASSUME that if there is no "Exceptions" topic / heading in the documentation for a constructor, then the constructor does NOT throw any?

A more complete way to document (constructors and methods) would be to ALWAYS include the heading "Exceptions" with the text "None" underneath (when applicable) -- this would (in my opinion) offer some clue as to whether or not an exception can be raised by the called constructor or method.

It is getting to the point where I now wrap nearly every call to every  constructor or method in a Try/Catch simply because I have no idea if an exception will be thrown!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a4afd65-db65-f52a-1e7a-88d7d90b8e21
* Version Independent ID: 563e3f81-a380-2693-6b8b-0a9b4834e1f9
* Content: [HttpRequestMessage Constructor (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httprequestmessage.-ctor#Windows_Web_Http_HttpRequestMessage__ctor_Windows_Web_Http_HttpMethod_Windows_Foundation_Uri_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httprequestmessage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httprequestmessage.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-01-05 03:54
Hi, @bdcoder2, this is a great question. Windows Runtime topics, as a rule, don't discuss exceptions at all, because the API design folks here strongly discourage them as part of the normal interface of calling WinRT APIs. However, while you're developing your own code, you may get exceptions thrown by your language projection of choice in cases where you pass invalid arguments. However, once you've caught and debugged those cases, and made corrections to your code, then you needn't expect to get further exceptions thrown during the normal execution of your released code. You may also be interested in this topic: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/error-handling. That topic is specific to the C++/WinRT language projection, but the ideas in there are generally valid, and are the recommended ones followed by folks implemented Windows Runtime APIs both inside and outside the company. Hope this helps! ~Steve

**Comment by bdcoder2** [comment] 2019-01-05 16:45
Hi, @stevewhims, Thank-you for your comment and link.  My issue is much more broad.  After nearly 50 years of programming, I can honestly say I have witnessed the steady decline of documentation.   In years gone past (prior to the concept of "Exceptions"), status codes were used to indicate success or failure and the documentation (usually) listed the status codes one could expect to handle.

Code is written using the available documentation as a guide.  More and more often, I am noticing that  the "Exceptions" topic has gone missing from MS documentation.

For example, the documentation for: [https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=netframework-4.7.2](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=netframework-4.7.2) lists very clearly what exceptions can be raised by the FileInfo constructor.

Going back to my original post, the documentation for HttpRequestMessage is missing the "Exceptions" topic - Why are these types of inconsistencies showing up in MS documentation?  A STANDARD template should be used and ALL topics should be present.

I have been burnt several times over recent years because the DOCUMENTATION never stated that an exception would be thrown because a value was outside a certain range or a combination of arguments would be considered invalid -- alas, when no mention of any type of exception being thrown is absent from the documentation, one cannot code for such cases; hence my comment about wrapping every call in a Try/Catch during development.

Just hoping that someone inside the MS documentation community would take the time to perhaps consider that documenting exceptions just might save those of us in the trenches some time and effort.  

End of Rant -- thanks again for your consideration.

**Comment by stevewhims** [comment] 2019-01-07 21:11
Hi, @bdcoder2, I definitely hear you about the importance of documentation quality, consistency, correctness, and (ultimately) usefulness. These qualities are dear to my heart, and I/we strive to fix issues of this kind whenever possible, and try to justify why we won't fix them when doing so isn't appropriate nor the best investment.

It's certainly by design that a Windows Runtime API topic doesn't have an "Exceptions" section. However, the FileInfo constructor topic is a .NET topic, and so the inconsistency that you're seeing is a consequence of them being different technologies, with different design characteristics. .NET is called from managed languages where exception support is guaranteed, whereas the Windows Runtime is an evolution of COM, and is incompatible at the binary level with exceptions. A Windows Runtime API at the application binary interface (ABI) level doesn't ever throw an exception. It always returns an HRESULT. However, sometimes a particular language projection turns an API's error HRESULT into an exception, and that's what you see as the consumer of that language projection. And if it's considered an error for a WinRT API's parameter argument to be outside of a range, then we do strive to document that constraint. And if there's a case where we don't do that, then that's a mistake on our part (that's NOT by design), and these GitHub issues are the right place to call us out on that, and we'll fix it. The specifics of how that error condition (going outside the range) surfaces is likely to be projection-specific, and not necessarily something it's cost-effective to include in every topic, and in any case the developer can avoid going outside the range once the range is known. The docs should include all the info (all of the "contract" of the API) that you need to know as a developer in order to call the API reliably and robustly in both debug and production code. As I say, if we've missed out any of that info, then we'll remedy it. But mentioning specific exceptions (which are inherently language projection-specific) is not a priority for the Windows Runtime docs.

**Comment by bdcoder2** [comment] 2019-01-07 22:18
Thanks again @stevewhims ! I should have been clear in my original post that I was referring specifically to ASP.Net documentation (not sure how my comment landed in the RT docs arena) -- I understand that the Windows Runtime API and ASP.Net framework are two different animals -- my issue was with the ASP.Net documentation as there seems to be a lack of documentation that describes what exceptions can be raised -- I usually go hunting for answers via the open source site.

Again, thanks for the clear explanation -- when I do come across classes with constructors and methods that are missing the "Exceptions" topic, I'll send in a note; at least then, if the docs are updated, it may help the next person who asks "I wonder what exceptions this will throw?..."

Cheers

**Comment by stevewhims** [comment] 2019-01-07 22:34
I see! Yes, I agree: if the "Exceptions" section is missing from a topic in a doc set where such sections are expected, then that'd be great if you could leave a note on the topic to give the writer a heads up to remedy that. And we appreciate your efforts there to help us improve the docs. Ok, so I'll go ahead and close this particular issue on this topic. Thanks again! :) ~Steve

**Closed as completed by stevewhims** 2019-01-07 22:34 UTC
