### ISSUE TITLE
But how can I get complete list of 16-bit service class UUIDs?

### ISSUE THREAD

**Issue by xixiaxixi** [MicrosoftDocs/winrt-api#1226] opened 2019-09-17 02:18 UTC
The complete list of 16-bit service class UUIDs(data type:0x03) is neither in `eventArgs.Advertisement.DataSections` nor in `eventArgs.Advertisement.ServiceUuids`.  

The doc says, property `ServiceUuids` is "The list of service UUIDs in 128-bit GUID format in a BluetoothLEAdvertisement." 

So how can I get complete list of 16-bit service class UUIDs in a Bluetooth LE advertisement watcher(`BluetoothLEAdvertisementWatcher`) callback event(`BluetoothLEAdvertisementReceivedEventArgs`)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f37be7c9-1772-b3d0-682e-72bff7cb0f82
* Version Independent ID: 54e3a8f9-1236-f3f9-c113-3331c46be412
* Content: [BluetoothLEAdvertisement Class (Windows.Devices.Bluetooth.Advertisement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by xixiaxixi** [comment] 2019-09-18 01:11
This is C# code
```
if (localName.Equals("xHC42"))
{
    Debug.WriteLine("HC42 scanned");

    Debug.WriteLine(String.Format("GUID(Count {0}): ", eventArgs.Advertisement.ServiceUuids.Count));
    foreach(var guid in eventArgs.Advertisement.ServiceUuids)
    {
        Debug.WriteLine(guid.ToString());
    }
    Debug.WriteLine(String.Format("DataSection(Count {0}): ", eventArgs.Advertisement.DataSections.Count));
    foreach(var section in eventArgs.Advertisement.DataSections)
    {
        Debug.WriteLine(String.Format("Type: {0:X02}", section.DataType));
        Debug.WriteLine("Data: " + IBufferToHexString(section.Data)); // String IBufferToHexString(IBuffer buffer)
    }
    Debug.WriteLine(String.Format("ManufacturerData(Count {0}): ", eventArgs.Advertisement.ManufacturerData.Count));
    foreach (var section in eventArgs.Advertisement.ManufacturerData)
    {
        Debug.WriteLine(String.Format("Type: {0:X04}", section.CompanyId));
        Debug.WriteLine("Data: " + IBufferToHexString(section.Data));
    }
}
```

This is C# result
```
HC42 scanned
GUID(Count 0): 
DataSection(Count 2): 
Type: 01
Data: 06
Type: 09
Data: 78 48 43 34 32
ManufacturerData(Count 0): 
```

This is a screenshot of a ble demo app on google play. 

![image](https://user-images.githubusercontent.com/24312323/65095442-c95b6080-d9f3-11e9-8b24-44d8bc6762a5.png)

The bluetooth module is a ble5.0 pass-through module named 'HC42'.

**Comment by stevewhims** [comment] 2019-09-20 17:28
Hi, @xixiaxixi, I've reached out to the feature team for input on this question. If they need the documentation to be updated, then I can do that. Thanks for filing the issue.

~Steve

**Comment by FrankGorgenyi** [comment] 2019-09-23 15:45
Hello xixiaxixi,

First thank-you for taking the time to provide such great information in the issue. We believe this is a defect and I have filed a work item on my team, we are not aware of a workaround unfortunately.

_OS Work Item 23527561: BluetoothLEAdvertisementReceivedEventArgs does not contain complete list of 16-bit service class UUIDs_

Secondly, you could speed up the resolution if you could provide [traces](https://github.com/Microsoft/busiotools/tree/master/bluetooth/tracing) that will let us narrow down the cause, so we don't need to spend time setting up a repro until validation. The traces will contain Bluetooth snoop logs so consider taking them on a test system.

Thanks,
Fg

**Comment by stevewhims** [comment] 2019-10-07 23:52
@xixiaxixi, are you able to provide the requested info? Just a reminder so that we can keep this issue fresh. ~Steve

**Comment by FrankGorgenyi** [comment] 2019-10-10 15:36
Hello @xixiaxixi ,

We are unable to reproduce this issue on current Windows Insider or later builds. You can either provided updated traces and we can provide the information to the appropriate team, or you can try a Windows Insider build.  Please help us help you.

Thanks,
Fg

**Comment by FrankGorgenyi** [comment] 2019-10-16 01:12
Hello @xixiaxixi ,

I've kept my internal issue open until I hear back from you either confirming it's not an issue in newer builds or that you still have a unique case. Can you please let me know either way? If not I'll close my internal issue.

Thanks,
Fg

**Comment by stevewhims** [comment] 2019-11-04 23:32
Hi, @xixiaxixi. I'll go ahead and close this issue now, since there's no further action we can take. Please reopen if you have the info that we need (described above). Thanks! ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:32 UTC
Labels: product-question
