### ISSUE TITLE
BackgroundDownloadProgress.TotalBytesToReceive always shows 0 after 1903

### ISSUE THREAD

**Issue by JimmyRespawn** [MicrosoftDocs/winrt-api#1106] opened 2019-05-28 06:25 UTC
download.Progress.TotalBytesToReceive is 0 after updating to 1903. I can still download, but TotalBytesToReceive always shows 0.
Seems this api is not working after May update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5efa67b-ecf2-b64f-e2e7-556524010817
* Version Independent ID: c092c8b8-499e-c03f-5692-01fb43ef1a6e
* Content: [BackgroundDownloadProgress.TotalBytesToReceive Field (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgrounddownloadprogress.totalbytestoreceive#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloadprogress.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloadprogress.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-05-31 19:08
Hi, @JimmyRespawn, the topic says "If this number is unknown, this value is set to 0." However, in your case, it sounds like the value *was* known prior to 1903. If you suspect a product bug, rather than a change in the platform that's uncovered an app bug, then here are some options.

The [Windows developer feedback site](https://wpdev.uservoice.com) is the right place to file a product bug, if you're certain there is one. For issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); in that case, a support engineer will look at the repro and see whether the issue is a product bug or something else. If it is a product bug, then you won't be charged. For problems/errors/omissions with the actual documentation about how Windows Runtime APIs work, this is the right forum to raise those, so if you do conclude that the docs need to be updated, then I'd really appreciate it if you could loop back here and let me know. In the meantime, I'll go ahead and close this issue. You'll be able to continue to comment on it, and/or re-open it, after that.

Thanks for filing this issue. ~Steve

**Closed as completed by stevewhims** 2019-05-31 19:08 UTC
Labels: support-request

**Comment by velocitysystems** [comment] 2019-07-29 13:09
@JimmyRespawn We also have experienced this and have posted it on the Windows Developer feedback forum. Please upvote if you can.

https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/38253688-backgrounddownloadprogress-totalbytestoreceive-is
