### ISSUE TITLE
No way to set PresharedKey for L2TP VpnNativeProfile

### ISSUE THREAD

**Issue by pulsegroupb2b** [MicrosoftDocs/winrt-api#1966] opened 2021-03-19 16:57 UTC
There is no way to set the preshared key for a VpnNativeProfile, here is how I have a connection setup using just need a way to add the preshared key

```
var vpnProfile = new VpnNativeProfile();
vpnProfile.AlwaysOn = true;
vpnProfile.NativeProtocolType = VpnNativeProtocolType.L2tp;
vpnProfile.ProfileName = "Vpn";
vpnProfile.RequireVpnClientAppUI = true;
vpnProfile.RememberCredentials = true;
vpnProfile.RoutingPolicyType = VpnRoutingPolicyType.ForceAllTrafficOverVpn;
vpnProfile.TunnelAuthenticationMethod = VpnAuthenticationMethod.PresharedKey;
vpnProfile.UserAuthenticationMethod = VpnAuthenticationMethod.PresharedKey;
vpnProfile.Servers.Add("[vpn ip]");

var vpnMa = new VpnManagementAgent();
status = await vpnMa.AddProfileFromObjectAsync(vpnProfile);
var cred = new Windows.Security.Credentials.PasswordCredential
{
    UserName = "[username]",
    Password = "[password]"
};
var op = await vpnMa.ConnectProfileWithPasswordCredentialAsync(vpnProfile, cred);
```

**Comment by stevewhims** [comment] 2021-03-23 20:59
===

Hi, @pulsegroupb2b, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions (or requests for help) regarding your specific scenario, like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action I can see that I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2021-03-23 20:59 UTC
Labels: product-question, Pri3
