### ISSUE TITLE
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.input.inking/inkstrokebuilder_createstrokefrominkpoints_2009821049.md

### ISSUE THREAD

**Issue by Ponant** [MicrosoftDocs/winrt-api#65] opened 2017-03-28 07:11 UTC

**Comment by mattwojo** [comment] 2017-03-29 23:56
Hi @Ponant -- Not quite sure what the issue is that you are seeking to raise here. Could you please clarify?  (Looks like you can find this markdown content on the live site [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkstrokebuilder#Windows_UI_Input_Inking_InkStrokeBuilder_CreateStrokeFromInkPoints_Windows_Foundation_Collections_IIterable_Windows_UI_Input_Inking_InkPoint__Windows_Foundation_Numerics_Matrix3x2_Windows_Foundation_IReference_Windows_Foundation_DateTime__Windows_Foundation_IReference_Windows_Foundation_TimeSpan__).)

**Comment by mattwojo** [comment] 2017-03-29 23:57
*Oh, looks like this is covered in the next issue you've filed... closing this one.

**Closed as completed by mattwojo** 2017-03-29 23:57 UTC
