### ISSUE TITLE
Cannot trigger this event when switching from a dock to laptop mode

### ISSUE THREAD

**Issue by laishiekai** [MicrosoftDocs/winrt-api#1241] opened 2019-09-25 22:38 UTC
Currently I am testing if my app still can change the display brightness after switching from dock mode (IsSupported==false) to regular laptop mode (IsSupported==true). I notice that if I start my app with dock mode (connected to two monitors) and remove the laptop from the dock, IsSupported will remain false. The event is not triggered either, at least in visual studio the break point in the callback function is not hit. If I start my app without using the dock, then IsSupported will be true. Am I using the event wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb1684d-bb79-3627-c972-5ab4614ca77d
* Version Independent ID: 463b829c-7042-8d45-508c-1701fa0d28eb
* Content: [BrightnessOverride.IsSupportedChanged Event (Windows.Graphics.Display) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride.issupportedchanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-09-26 00:34
Hi, @laishiekai, thanks for reaching out with this issue. I experimented on my laptop (and on a desktop PC), but I wasn’t able to get a case like yours where the event was raised, so I couldn't determine whether or not the property value had changed. Unfortunately, then, from my experiments, I'm not seeing the unexpected API behavior that you're seeing.

In any case, For problems/errors/omissions *with the actual documentation* about how Windows APIs work, this feedback mechanism (**Send feedback about** \> **This page**) takes you to the right place to raise those.

But this particular issue doesn't look like something that I can fix by making a change to the docs. It's really a question, it seems, as to whether the APIs are behaving as specified. I don't myself see any issue with the content itself, based on my experiments (although I understand that you're seeing unexpected behavior). So, if instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below). Or, if you believe that this is a product bug, then see the fourth option below, about Microsoft Support.

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by laishiekai** [comment] 2019-09-26 23:08
Thank you for your quick response! I feel like it might be the way I use the API. I have posted a question on SO: 
https://stackoverflow.com/questions/58124485/brightnessoverride-issupportedchanged-is-not-triggered-when-i-switch-the-monitor

**Comment by stevewhims** [comment] 2019-10-07 23:51
Great! I'll go ahead and close this issue. ~Steve

**Closed as completed by stevewhims** 2019-10-07 23:51 UTC
Labels: product-question
