### ISSUE TITLE
Usage of VpnPacketBuffer.AppId Property

### ISSUE THREAD

**Issue by bdbai** [MicrosoftDocs/winrt-api#1798] opened 2020-09-02 07:07 UTC
I was trying to use `VpnPacketBuffer.AppId` Property to get the app ID from my `IVpnPlugIn.Encapsulate` method for further processing with these packets. However, all `VpnPacketBuffer`s flowed through the VPN interface carried a null `AppId`. I guess it was because no `VpnTrafficFilter` was set, so I added some to see if it works.

When all `VpnTrafficFilter`s contain `VpnAppId`s for packaged apps only, I was able to get `AppId`s from the `VpnPacketBuffer`s. When all `VpnTrafficFilter`s contain `VpnAppId`s for win32 apps only, no `VpnPacketBuffer` carried a `AppId`. When mixed `VpnTrafficFilter` was set, a memory access violation occurred from `Windows.Networking.Vpn.dll` and crashed the whole VPN process while the plugin was accessing the `VpnPacketBuffer.AppId` Property. 

What is the correct way to use this property?

cc @PeterSmithRedmond 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db4b4248-bdf3-e556-7aed-f99ddf8de4d3
* Version Independent ID: 457c8c09-b04e-6342-74de-8dd94a1e3efb
* Content: [VpnPacketBuffer.AppId Property (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnpacketbuffer.appid?view=winrt-19041#Windows_Networking_Vpn_VpnPacketBuffer_AppId)
* Content Source: [winrt-api-build/xml/Windows.Networking.Vpn/VpnPacketBuffer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Vpn/VpnPacketBuffer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-09-02 19:15
Hi, @bdbai, and thanks for filing this issue. I've sent a message to the feature team to see whether they can help provide the answer. I'll be happy to update the topic with any missing info.

Thanks again!
Steve

**Comment by stevewhims** [comment] 2020-12-11 00:48
Hi, @bdbai, and sorry for the delay. We're still discussing this internally, and I hope to have an answer soon.

Thanks!
Steve

**Comment by bdbai** [comment] 2020-12-11 00:53
Hi Steve! It's good to hear that this issue is still making progress. Please kindly update once you guys come to any conclusions. Thanks!

**Comment by stevewhims** [comment] 2021-02-09 03:36
UPDATE: I've just sent another email to the internal thread asking for the last bit of clarification. Hopefully I'll be able to respond soon. Sorry for the delay!

-Steve

**Comment by stevewhims** [comment] 2021-03-12 22:44
UPDATE: The feature team are talking about this internally, I'm just still asking them for a crisp answer I can give here. Thanks for your patience.

-Steve

**Comment by stevewhims** [comment] 2021-03-26 23:42
UPDATE: It's looking like we're able to reproduce a data corruption that's causing the crash you saw. I think for the time being (that is, until the root cause of the issue can be located and corrected within the platform), it seems safest to avoid using Win32 appids at all. I'll go ahead and close this issue simply because it's not something we're in a position to document yet (since we're still investigating). You can continue to update the thread, though, as can I, and I'll reactivate it (and/or update it) in the event that we reach a resolution and/or have something crisp to say in the docs.

Thanks again!
Steve

**Closed as completed by stevewhims** 2021-03-26 23:42 UTC
Labels: product-question, winrt-reference/tech, uwp/prod, Pri2
