### ISSUE TITLE
Intellisense indicates that the ParentServices property is obsolete but this documentation does not

### ISSUE THREAD

**Issue by peterfoot** [MicrosoftDocs/winrt-api#673] opened 2018-10-19 16:21 UTC
Intellisense in Visual Studio indicates that this property is obsolete. It is not marked as obsolete in this documentation nor are there any possible alternative properties/methods. Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc505d5-e14a-1b0c-506a-01b992da77d8
* Version Independent ID: 4f46133a-a537-e279-87dc-c0cf6966f8c9
* Content: [GattDeviceService.ParentServices Property (Windows.Devices.Bluetooth.GenericAttributeProfile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattdeviceservice.parentservices#Windows_Devices_Bluetooth_GenericAttributeProfile_GattDeviceService_ParentServices)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattdeviceservice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattdeviceservice.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2019-10-23 01:09
Hi, @peterfoot. Thanks for filing this issue, and my apologies for the very long delay in responding.

I have added this detail to the topic now (that should be live soon). But I don't have info about any alternative API. It might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:56
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:56 UTC
