### ISSUE TITLE
UnauthorizedAccessException in HttpDiagnosticProvider - UWP

### ISSUE THREAD

**Issue by Kumara-Krishnan** [MicrosoftDocs/winrt-api#1273] opened 2019-10-19 12:26 UTC
I'm trying to trace network calls in UWP. I am trying to use HttpDiagnosticProvider. Here's my code.

```
var processDiagnosticsInfo = ProcessDiagnosticInfo.GetForCurrentProcess();
var httpDiagnosticProvider = HttpDiagnosticProvider.CreateFromProcessDiagnosticInfo(processDiagnosticsInfo);
httpDiagnosticProvider.ResponseReceived += OnResponseReceived;
httpDiagnosticProvider.Start();
```

I'm getting UnauthorizedAccessException in Start() method. What's wrong with my code or do i need to get user grant or something to make it work? Already asked on stackoverflow - https://stackoverflow.com/questions/57990868/unauthorizedaccessexception-in-httpdiagnosticprovider-uwp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c2f9a1e-e7f1-098a-83ce-a1b246901f2f
* Version Independent ID: 6fd96e99-9ae1-c128-3430-7a9171f5d1bb
* Content: [HttpDiagnosticProvider Class (Windows.Web.Http.Diagnostics) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.diagnostics.httpdiagnosticprovider#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.diagnostics.httpdiagnosticprovider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.diagnostics.httpdiagnosticprovider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-10-21 20:56
Hi, @Kumara-Krishnan, thanks for filing this issue. It looks like the feature team is engaged on your StackOverflow thread, so it's probably best to keep prompting for a response there. I wouldn't recommend beginning a duplicate support thread about this, since it'll likely end up being routed to the same feature team, and they're presumably already working the case in the background. However, if you do want to do that, then here's further info. 

This feels not so much like feedback specifically about the documentation, but rather like a question about the product. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

Thanks!
Steve

**Closed as completed by stevewhims** 2019-10-21 20:56 UTC
