### ISSUE TITLE
Is there a way to disconnect a connection from server?

### ISSUE THREAD

**Issue by 13xiaobang** [MicrosoftDocs/winrt-api#2224] opened 2022-05-20 06:31 UTC
[Enter feedback here]
After setting service/characteristics and do serviceProvider.StartAdvertising(), then client connect the server. How can server do **disconnect** to  a client ? I did't find any api in Docs.

In a word, what I want is the method for server to:
1. disconnect a connection from a single client, the service is still available and can be connected, and other client's connection is still work.
2. disconnect all client connection, and the service is not avaliable. (seems serviceProvider.StopAdvertising() useful, but after I tried, the client did not get disconnect event?)

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f677583-fed4-e682-f4c7-82164ee2396d
* Version Independent ID: c7db60e9-62e5-6d94-c09c-99cc4d31203d
* Content: [GattServiceProvider Class (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceprovider?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattServiceProvider.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattServiceProvider.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-05-20 20:56
Hi, @13xiaobang, and thanks for filing this issue.

For feedback about missing, incorrect, or incomplete info in a particular topic, you can visit the topic and then **Send feedback about** \> **This page**.

For questions/feedback/support about the platform (Windows and its APIs) or tools (such as "How do I do [...]"), you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info/questions above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since it doesn't look like we're identifying any specfic documentation that's wrong. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-05-20 20:56 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2

**Comment by stevewhims** [comment] 2022-06-18 01:04
UPDATE: I added a [Remarks](https://docs.microsoft.com/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceprovider) section to the topic, explaining the lack of disconnect functionality.

-Steve

**Comment by 13xiaobang** [comment] 2022-06-20 12:12
@stevewhims
Thanks, I have read the remark，but I think you did not memtion why we want to disconnect connections as a peripheral device.

Think about it , as a peripheral device A, it publish its service by advertising(). Then central B  and central C both establish connections to device A, and try to use service from device A. If device A have a black list that shows centeral B is illegal(judge from BLE mac address or sth else) that it has no permission to use service, central C is permitted.Then how can device A do now if it can not disconnect to central B? What it can do is just ignore command from device B? Why could it can not disconnect connection to central B to save some resources?
In another way, Android platform can disconnect as a BLE peripheral , so I do think it is realizable, and it is widely used.（https://developer.android.com/reference/android/bluetooth/BluetoothGattServer#cancelConnection(android.bluetooth.BluetoothDevice)）Maybe windows api have a long way to go to fulfil it.

**Comment by stevewhims** [comment] 2022-06-20 17:56
Thanks, @13xiaobang! I'll pass your comment along (and as always I'll update the documentation if I'm directed to). But because my role is really just documentation (rather than the platform/feature/APIs themselves), you will have more luck if you use the feedback mechanisms I mention above when you have feedback about the APIs (rather than about the docs).

Thanks again!
-Steve

**Comment by 13xiaobang** [comment] 2022-06-21 10:29
@stevewhims OK, I know it.
