### ISSUE TITLE
BarcodeScanner.FromIdAsync sometimes returns null for no obvious reason

### ISSUE THREAD

**Issue by JasperE84** [MicrosoftDocs/winrt-api#926] opened 2019-02-17 13:16 UTC
BarcodeScanner.FromIdAsync() returns some unexpected results in my UWP app.

When using a SocketScan D730 Bluetooth barcode scanner, BarcodeScanner.FromIdAsync() works fine if my scanner is turned on when I call FromIdAsync() is called for the first time. I can then claim and use the device (as expected).

However, if I first call FromIdAsync() while the scanner is turned -off-, then the function returns null (as expected)
If I then turn the scanner -on- again, and then run FromIdAsync() again, the function still returns null (that's unexpected).
Sometimes it takes a bunch of tries before FromIdAsync() returns a BarcodeScanner object. Sometimes it will just keep returning null.

If I restart my app and run FromIdAsync(), without having rebooted my scanner, a BarcodeScanner object is immediately returned and works every time (expected).

For reference I have created a GitHub gist containing my BarcodeService class: https://gist.github.com/JasperE84/3c0fe2be1535f2738ded885b9edf4922
This code sample will return the log message at line nr. 245 numerous times before successfully returning a BarcodeScanner object to claim.

Can anyone explain this behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fbf7620-25a1-a292-60e4-8fe6f1685d7c
* Version Independent ID: 491c7914-18ab-c768-cd63-3304cd0a1dc0
* Content: [BarcodeScanner.FromIdAsync(String) Method (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.barcodescanner.fromidasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescanner.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescanner.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment] 2019-10-22 01:36
Hi, @JasperE84. Thanks for filing this issue, and my apologies for the very long delay in responding.

This feels like a support question about the product, rather than feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:59
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:59 UTC
