### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by ericcox** [MicrosoftDocs/winrt-api#576] opened 2018-08-25 03:29 UTC
Please flesh out the Exceptions section: what exceptions might be thrown, and what do they mean?   In my case, I can select a file fine using PickSingleFileAsync, but when I use GetFileFromPathAsync I get System.UnauthorizedAccessException, and I have no idea why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a0b142-3819-3929-bc93-c4d8e0598978
* Version Independent ID: 932a8fe2-dc4e-ade9-e67d-45897840c037
* Content: [StorageFile.GetFileFromPathAsync(String) Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.StorageFile.GetFileFromPathAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Felix-Dev** [comment] 2018-12-10 17:47
@ginami @laurenhughes 
Please assign someone to this issue who can actually address it. It is a) unacceptable that a public API method can throw undocumented exceptions and b) even after it was reported months ago, ZERO progress has been made.

I don't want to criticize your system here (and I really can't since I'm not seeing the big picture), but I do wonder whether you guys actually have a system in place which checks if the assigned authors actually do comment/work on "their" issues? Too often, once someone has been assigned to an issue, it is left behind to rot in the grave while seemingly no one at Microsoft seems to care.

Appreciate your comment!

**Comment by jillre** [comment] 2018-12-10 21:21
Hi @Felix-Dev. Thanks for commenting on the issue (and thanks, @ericcox for filing it). I am very sorry that we did not respond to it in a timely manner. We are working out our processes for ownership of issues, particularly when ownership of the associated content changes, as was the case here. Please accept my sincere apology for letting some things slip through the cracks. We do our best to address issues that come in, but we need to do better. 

To you specific question about an Exceptions section in this document, generally speaking, Windows Runtime APIs are designed not to throw exceptions of the kind that we expect deployed code to handle at runtime. That's why the docs are not in the habit of mentioning them. However, there are some cases where that rule is not followed. We have sent your findings to the product team and will respond back with their guidance, and then we’ll work with them on whether/what to document here regarding exceptions.

**Comment by Felix-Dev** [comment] 2018-12-10 23:16
@jillre,
thank you for your fast response! Seeing the number of issues filed all the time and that you guys also have your own priorities (writing new API documentation,...) I can see that sometimes it might be a bit overwhelming for the team and some issues, especially in the cases you mentioned, end up being forgotten.
It's nice to see that you are aware of some of the causes for the issue-backlog! And just to clarify, I don't demand every issue to be fixed/worked on immediately after it was filed (which would be a huge demanding task coupled with all your other work). Just, a timely comment by a Docs team member if the issue is being looked at (or not being worked on for whatever reason) would be appreciated a lot 🙂 

As for the specific question: The issue for me here stemmed from the fact that a rather similar method has its exceptions detailed whereas it is missing for this specific method. See [StorageFolder.GetFolderFromPathAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getfolderfrompathasync). So for the sake of consistency I was advocating to include thrown exceptions for this particular method too. (I suspect, given the close proximity of these two methods, that they are (nearly) identical.)

Thank you again for your timely response!
Felix

**Comment by jillre** [comment] 2018-12-10 23:39
@Felix-Dev thanks for the link to [StorageFolder.GetFolderFromPathAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getfolderfrompathasync). That's helpful.

**Comment by mcleanbyron** [comment] 2018-12-13 18:31
Thanks for the feedback! StorageFile.GetFileFromPathAsync does share the same general exception cases as StorageFolder.GetFolderFromPathAsync, and I have updated [StorageFile.GetFileFromPathAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathasync) with the exceptions and added a link to an article about file access permissions for the UnauthorizedAccessException. I have an open thread going with the engineering team about whether there are further exceptions we need to document for these, and I will revise the articles further as necessary. However, since the original feedback has now been addressed, I'm closing this issue. Again, we apologize that this issue lingered on our backlog for so long.

**Closed as completed by mcleanbyron** 2018-12-13 18:31 UTC
