### ISSUE TITLE
PairAsync method works against Bluetooth LE standard?

### ISSUE THREAD

**Issue by beavis88** [MicrosoftDocs/winrt-api#2104] opened 2021-11-03 08:11 UTC
I have tried PairAsync using DevicePairingKinds.ConfirmOnly custom pairing method and all kinds of DevicePairingProtectionLevel parameter value. I tried to pair BLE device requiring 'just works' pairing method without bonding and every time Windows reports successful pairing result with ProtectionLevelUsed == DevicePairingProtectionLevel.None, but actually BLE device rejects pairing because windows BLE stack every time requested bonding (LTK). How to avoid bonding request using winrt api?

**Comment by stevewhims** [comment] 2021-12-02 02:38
Hi, @beavis88, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For questions (or requests for help) regarding your specific scenario, like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2021-12-02 02:38 UTC
Labels: product-question, Pri3
