### ISSUE TITLE
ConnectionProfile.ProfileName does not return a readable name. 

### ISSUE THREAD

**Issue by Akshay-Kumar-S** [MicrosoftDocs/winrt-api#2273] opened 2022-08-10 06:09 UTC
ConnectionProfile.ProfileName does not return a readable name. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb33355-8a57-75ea-9062-c62dd25fb2de
* Version Independent ID: 1843981e-041d-6eff-1c9d-5902e31b765c
* Content: [ConnectionProfile.ProfileName Property (Windows.Networking.Connectivity) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.connectionprofile.profilename?view=winrt-22621#windows-networking-connectivity-connectionprofile-profilename)
* Content Source: [winrt-api-build/xml/Windows.Networking.Connectivity/ConnectionProfile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Connectivity/ConnectionProfile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-08-11 00:15
Hi, @Akshay-Kumar-S, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete. But as far as I know, the description of this API does correctly reflect the intent of its functionality. So we wouldn't want to change the documentation here.

For questions or feedback (or requests for help) regarding how an API functions, as in this case, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-08-11 00:15 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
