### ISSUE TITLE
Setting default headers causes concurrent access errors (E_CHANGED_STATE)

### ISSUE THREAD

**Issue by martinraiberfc** [MicrosoftDocs/winrt-api#2410] opened 2023-10-12 11:47 UTC
Setting default headers _before_ using a httpclient causes concurrent access errors (E_CHANGED_STATE: A concurrent or interleaved operation changed the state of the object, invalidating this operation.).

To reproduce see following example: https://gist.github.com/martinraiberfc/46ad7fc6e5c6e2516f09f78d1e234f3e

This perhaps needs to be documented or somehow fixed. As a work-around the headers can be set via a custom request filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b195d006-dff9-0a63-7008-3f50887c3be9
* Version Independent ID: a2f8a231-97e4-6f69-7100-93e19171ecb5
* Content: [HttpClient.DefaultRequestHeaders Property (Windows.Web.Http) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.defaultrequestheaders?view=winrt-22621#windows-web-http-httpclient-defaultrequestheaders)
* Content Source: [winrt-api-build/xml/Windows.Web.Http/HttpClient.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web.Http/HttpClient.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2023-10-12 18:09
Thanks, @martinraiberfc. I'll investigate whether the behavior is considered a bug or not.

-Steve

**Comment by stevewhims** [comment] 2023-11-15 17:44
UPDATE: Thanks for your patience: we can't reproduce the issue as described. So I'll go ahead and close this for now, but we can reopen if it different data comes in.

Thanks!
-Steve

**Closed as completed by stevewhims** 2023-11-15 17:44 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2

**Comment by JunielKatarn** [comment] 2024-06-04 00:23
@stevewhims FYI. We have encountered this bug while developing a feature for React Native Windows. Had to implement a workaround.

The bug is intermittent, but we'll try to come up with a consistent reproducible case.

**Comment by uroni** [comment] 2024-10-30 11:13
@JunielKatarn How did you workaround this issue? We worked around it by setting the HTTP headers in each request. The problem is that I guess that makes the multi-threading bug just harder to hit and we are currently running into this with wider testing.
