### ISSUE TITLE
How to HTTP Post a File in WinRT?

### ISSUE THREAD

**Issue by Mt-Perazim** [MicrosoftDocs/winrt-api#2216] opened 2022-05-03 07:38 UTC
I am having a hard time understanding how to make an HTTP post request in WinRT. I have an ASP.Net 6 Web Api, which I have already been able to access via a Python project and a C++ project (via Curl). The api can also be tested via Postman.

But now I have a WinRT project and have thrown together the following code. I want to be able to upload a file. In my case it is a point cloud in .ply format. 

My Question:
1. Can someone tell me if this is the right way? Especially the lines 
`binaryContent.Headers().Append(L"Content-Type", L"image/jpeg");` and
`HttpContentDispositionHeaderValue disposition{ L"form-data" };`
```
    void HL2ResearchMode::SendPLY(std::wstring const& pointCloud)
    {
        OutputDebugString(L"--- SendPLY()\n");

        if (pointCloud.size() == 0)
            return;

        init_apartment();

        auto buffer{
            winrt::Windows::Security::Cryptography::CryptographicBuffer::ConvertStringToBinary(
                pointCloud,
                winrt::Windows::Security::Cryptography::BinaryStringEncoding::Utf8
            )
        };

        winrt::Windows::Web::Http::HttpBufferContent binaryContent{ buffer };
        // binaryContent.Headers().Append(L"Content-Type", L"text/plain;charset=utf8");
        binaryContent.Headers().Append(L"Content-Type", L"image/jpeg");

        winrt::Windows::Web::Http::Headers::HttpContentDispositionHeaderValue disposition{ L"form-data" };
        //winrt::Windows::Web::Http::Headers::HttpContentDispositionHeaderValue disposition{ L"multipart/form-data" };
        binaryContent.Headers().ContentDisposition(disposition);
        disposition.Name(L"fileForUpload");
        disposition.FileName(L"test.ply");

        winrt::Windows::Web::Http::HttpMultipartFormDataContent postContent;
        postContent.Add(binaryContent);

        winrt::Windows::Web::Http::HttpResponseMessage httpResponseMessage;
        std::wstring httpResponseBody;

        try
        {
            // Send the POST request.
            winrt::Windows::Foundation::Uri requestUri{ L"https://192.168.178.41:5001/api/meshes/uploadPointCloud" };
            winrt::Windows::Web::Http::Filters::HttpBaseProtocolFilter myFilter;

            auto fu = myFilter.IgnorableServerCertificateErrors();
            fu.Append(ChainValidationResult::Expired);
            fu.Append(ChainValidationResult::Untrusted);
            fu.Append(ChainValidationResult::InvalidName);
            fu.Append(ChainValidationResult::InvalidSignature);
            fu.Append(ChainValidationResult::InvalidCertificateAuthorityPolicy);

            winrt::Windows::Web::Http::HttpClient httpClient(myFilter);
            httpResponseMessage = httpClient.PostAsync(requestUri, postContent).get();
            httpResponseMessage.EnsureSuccessStatusCode();
            httpResponseBody = httpResponseMessage.Content().ReadAsStringAsync().get();
        }
        catch (winrt::hresult_error const& ex)
        {
            httpResponseBody = ex.message();
        }
        std::wcout << httpResponseBody;
    }
```
2. What are the follow lines for? Is this about assigning arbitrary names?
```
disposition.Name(L"fileForUpload");
disposition.FileName(L"test.ply");
```

**Comment by stevewhims** [comment] 2022-05-17 00:56
Hi, @arsi0001, and thanks for filing this issue.

For feedback about missing, incorrect, or incomplete info in a specific topic, you can visit the topic and then **Send feedback about** \> **This page**.

For questions/feedback/support about the platform (Windows and its APIs) or tools, you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since it doesn't look like we're identifying any documentation that's wrong. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-05-17 00:56 UTC
Labels: Pri3
