### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by gtbuchanan** [MicrosoftDocs/winrt-api#511] opened 2018-07-30 19:53 UTC
Fails to mention that the dictionary keys are case-sensitive ~~and are all lower case~~.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed55d14-2142-14c7-3986-7bcf97f0be4d
* Version Independent ID: 566a25f4-8e73-d95f-e4f4-fe966c8ad297
* Content: [ResponseInformation.Headers Property (Windows.Networking.BackgroundTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.responseinformation.headers)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.responseinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.responseinformation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2018-07-30 21:06
Thanks, @gtbuchanan, I'll get that updated asap. ~Steve

**Comment by stevewhims** [comment] 2018-08-03 18:30
I've just merged a fix into master; I expect that to appear on the live topic within 24 hours.

**Comment by stevewhims** [comment] 2018-08-10 19:09
Thanks again for the heads up, @gtbuchanan. The fix is now live so I'll close this issue. Please reopen if necessary. ~Steve

**Comment by gtbuchanan** [comment] 2018-11-14 14:49
@stevewhims Do you know if this behavior changed between different UWP versions? If that's the case, then we'll probably need to reopen this issue.

I recently upgraded my UWP target versions, but then I started seeing different behavior between two different clones of the same repository. One older clone only allowed lower-case keys, but the newer clone only allowed pascal-case keys (`Content-Type` vs `content-type`). Once I cleaned unversioned files from the older clone, it started showing the same pascal-case key behavior as the newer clone. I'm guessing the older clone had some cached DLLs from an older version or something...

**Comment by stevewhims** [comment] 2018-11-14 20:46
Thanks, @gtbuchanan, I've reopened the issue until we get resolution and I've pinged the product team for info. ~Steve

**Comment by gtbuchanan** [comment] 2018-11-14 22:13
Thanks, Steve. I think I've gotten to the bottom of the issue. It appears I was initially incorrect in stating that UWP converts the headers to lower case. This was just a side affect of one of our servers being on Windows Server 2016 and defaulting to HTTP/2 [which sends headers in all lower case](https://forums.iis.net/t/1234149.aspx?IIS+10+win2016+headers+converted+to+lowercase+when+requested+via+HTTPS). The other server is still on Windows Server 2012 R2 and defaulting to HTTP/1.1 which sends the headers in pascal case.

Unfortunately, this means the `Headers` dictionary can be inconsistent depending on the configuration of the server it's communicating with. The docs will likely need to be updated to remove the statements about converting to lower case. Alternatively, I would ask that you submit a ticket to the product team to either actually convert to lower case (since that's the standard for HTTP/2) or make the `Headers` dictionary use a case-insensitive comparer.

**Comment by stevewhims** [comment] 2018-11-15 00:07
The idea of making the dictionary lookup case-insensitive has been favorably received, @gtbuchanan, so thanks!  :) I'll leave this issue open until that change happens and is publicly released whereupon I'll update this topic again. So, to confirm, there weren't any recent changes… the server and/or HTTP version determines what case the client receives. I'll also update this topic now to remove the bit about converting to lower-case. ~Steve

**Comment by stevewhims** [comment] 2020-06-03 00:58
I'll go ahead and close this issue. We're not now planning to do the work of making the dictionary lookup case-insensitive, so there's no opportunity here to update content.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

-Steve

**Closed as completed by stevewhims** 2020-06-03 00:58 UTC
Labels: doc-enhancement, windows/prod, Pri2
