### ISSUE TITLE
Need method to retrieve WIFI Direct AutoGO's SSID

### ISSUE THREAD

**Issue by yanfangliu-google** [MicrosoftDocs/winrt-api#2235] opened 2022-06-10 17:22 UTC
I am building a WIFIDirect APP with WinRT in C++. I can start an Auto GO(not legacy softAP mode) without problem and I can see the SSID by doing WIFI Scan with my phone. I want send this Auto GO's SSID to another device through BT or BLE(not just by eyes), but I can't find an API to query this local Auto GO's SSID. I wonder if this API is exist in WRT or not. If yes, what it is. If not, is there any plan MS will provide it?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a5cf94-51ec-cd01-8b27-0aba51a9daf9
* Version Independent ID: 28e4251e-0627-ebf5-5a90-3a377b4557ba
* Content: [WiFiDirectDevice Class (Windows.Devices.WiFiDirect) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifidirect.wifidirectdevice?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.WiFiDirect/WiFiDirectDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.WiFiDirect/WiFiDirectDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-06-10 17:45
Hi, @yanfangliu-google, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

But for questions about the feature or product, like this, you can click **Send feedback about** \> **This product** (instead of **This page**), and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-06-10 17:45 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2

**Comment by yanfangliu-google** [comment] 2022-06-10 18:11
Thanks for point out. I've already asked here:
https://docs.microsoft.com/en-us/answers/questions/885084/34wi-fi-direct-sample34-need-a-wayapi-to-retrieve.html
