### ISSUE TITLE
 await ble_Device.GetGattServicesAsync(BluetoothCacheMode.Uncached) 返回值太慢，返回失败率太高设备不可访问

### ISSUE THREAD

**Issue by xiazx** [MicrosoftDocs/winrt-api#2359] opened 2023-03-31 07:54 UTC
[在此处输入反馈] == [Enter feedback here]

The title machine-translates to "await ble_Device.GetGattServicesAsync(BluetoothCacheMode.Uncached) The return value is too slow, the return failure rate is too high and the device is inaccessible".

文档详细信息
⚠ 请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。
•	ID: 69411ce9-8593-48a8-4b9c-ff6d34a95720
•	Version Independent ID: bbda6169-0dd1-d876-1f1e-8c9e1dd3e2d1
•	Content: [BluetoothLEDevice.GetGattServicesAsync 方法 (Windows.Devices.Bluetooth) - Windows UWP applications](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fzh-cn%2Fuwp%2Fapi%2Fwindows.devices.bluetooth.bluetoothledevice.getgattservicesasync%3Fview%3Dwinrt-22621&data=05%7C01%7CSteven.White%40microsoft.com%7Cd0863155fec4474866a108db31bd3adf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638158461053162075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2TV%2BNVxOpOTaW47k3dsQrjvMW4vQqeonBEPeCEA0ubA%3D&reserved=0)
•	Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwinrt-api%2Fblob%2Fdocs%2Fwinrt-api-build%2Fxml%2FWindows.Devices.Bluetooth%2FBluetoothLEDevice.xml&data=05%7C01%7CSteven.White%40microsoft.com%7Cd0863155fec4474866a108db31bd3adf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638158461053162075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xSh1uNcTu1A9TwIZ8d%2FATJCq7eHKnFhyCEaRpC4nlos%3D&reserved=0)
•	Product: uwp
•	Technology: winrt-reference
•	GitHub Login: @stevewhims
•	Microsoft Alias: stwhi

**Comment by stevewhims** [comment] 2023-03-31 18:57
Reply provided in English first, and then (machine-translated) Chinese afterward. 先用英文回复，再用中文（机器翻译）回复。

Hi, @xiazx, and thanks for filing this issue. It sounds like when calling this API to retrieve services that are in the uncached mode, the performance of the API is slower than you'd like (along with other issues).

The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For questions (or requests for help) regarding the product itself (the operating system and its APIs), one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Since there doesn't seem to be any action to take to improve the docs, I'll go ahead and close the issue.

Thanks!
-Steve

---

嗨，@xiazx，感谢您提出这个问题。 听起来好像在调用此 API 以检索处于未缓存模式的服务时，API 的性能比您希望的要慢（以及其他问题）。

您在此处使用的反馈渠道（**提交并查看针对 ** \> **此页面** 的反馈）是针对已发布的本主题本身文档的反馈。 例如，如果内容不正确或不完整。

对于有关产品本身（操作系统及其 API）的问题（或请求帮助），一种选择是单击 **提交并查看反馈** \> **此产品**，您将被 到 [微软问答](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all)。

为了完整起见，这里是所有开发人员支持资源。
- [Microsoft 问答](https://docs.microsoft.com/answers/topics/windows-uwp.html) 是游说更改或新功能、提出建议或询问产品的正确场所 问题。
- 对于开发问题的社区帮助，有我们的 [论坛](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) 和 [StackOverflow](https://stackoverflow .com/问题）。
- [Windows 开发人员支持](https://developer.microsoft.com/windows/support) 网站解释了其他支持选项。
- [Visual Studio 开发人员社区](https://developercommunity.visualstudio.com) 可用且响应迅速。 以前的用户语音功能现在位于**建议功能**选项卡上，如果您想游说更改、功能或提出建议。
- 对于开发者问题，或疑似产品错误，有 [Microsoft 支持](https://support.microsoft.com/contactus)； 支持工程师会查看重现，看看问题是 Microsoft 产品错误还是其他问题。 如果它是 Microsoft 产品的错误，那么票证将是免费的。

由于似乎没有任何可采取的措施来改进文档，我将继续并关闭问题。

谢谢！
-史蒂夫

**Closed as completed by stevewhims** 2023-03-31 18:57 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
