### ISSUE TITLE
RfcommDeviceService is not working

### ISSUE THREAD

**Issue by yushuohuanxiu** [MicrosoftDocs/winrt-api#1677] opened 2020-06-06 23:40 UTC
[在此处输入反馈]
My application scenario looks like this, I have a Bluetooth headset that has been connected and paired with my Windows 10 PC, and "Hands-free AG" and "Stereo" are in the play device list.What I want to do is to get the RFCOMM connection between the "Hands-free AG" device and the Bluetooth headset (this connection has been established by the windows, and my program does not need to manage connection actions), and then listen to the communication content on this RFCOMM connection, so as to get information such as Bluetooth headset battery info.
Using UWP API "Windows.Devices.Bluetooth.Rfcomm " namespace, can support me to complete the work? Or do I need to do driver development to achieve it?

my code is like this:

BluetoothDevice bluetoothDevice = await BluetoothDevice.FromIdAsync("Bluetooth#Bluetooth10:63:c8:79:64:fe-78:a7:eb:ea:19:21");
RfcommDeviceServicesResult rfcommDeviceServicesResult = await bluetoothDevice.GetRfcommServicesAsync();
RfcommDeviceService service = rfcommDeviceServicesResult.Services[0];
IReadOnlyDictionary<UInt32, IBuffer> attributes = await service.GetSdpRawAttributesAsync();
 foreach (KeyValuePair<UInt32, IBuffer> kvp in attributes)
 {
    var attributeReader = DataReader.FromBuffer(kvp.Value);
    var attributeType = attributeReader.ReadByte();
    Debug.WriteLine("Key = {0}, Value = {1}", kvp.Key, attributeType);
}
StreamSocket chatSocket = new StreamSocket();
await chatSocket.ConnectAsync(service.ConnectionHostName, service.ConnectionServiceName);

in this code, the RfcommDeviceService 's DeviceAccessInformation attr is "DeniedBySystem", and the chatSocket.ConnectAsync Fun is error  hresult 0x80070005.

did any advice for me?
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5bc2041f-aad6-6055-8333-b193fb24d483
* Version Independent ID: dedab901-c218-88f6-82d1-452f2c0c55d1
* Content: [Windows.Devices.Bluetooth.Rfcomm Namespace - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.devices.bluetooth.rfcomm?view=winrt-19041)
* Content Source: [winrt-api-build/xml/ns-Windows.Devices.Bluetooth.Rfcomm.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Devices.Bluetooth.Rfcomm.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-06-09 00:28
Hi, @yushuohuanxiu, and thanks for filing this issue. The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions (or requests for help) regarding your specific scenario, like this, one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve

**Closed as completed by stevewhims** 2020-06-09 00:28 UTC
Labels: support-request, winrt-reference/tech, uwp/prod
