### ISSUE TITLE
HoloLens VPN With Smart Card

### ISSUE THREAD

**Issue by jjherman94** [MicrosoftDocs/winrt-api#572] opened 2018-08-22 18:43 UTC
I've noticed on the HoloLens when setting up a VPN there is an option to set the VPN type to smart card. Is this actually correct and if so what kind of smart card readers work with the HoloLens? Do they have to connect through the micro usb port?

![20180822_135943_hololens](https://user-images.githubusercontent.com/5394456/44483646-e236ee00-a608-11e8-931c-5da5e44b8775.jpg)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be87447c-d313-8ac5-3ea1-8deb5098792d
* Version Independent ID: 53ba1199-da1b-72ed-09d2-2c4f2f1cc960
* Content: [VpnCredentialType Enum (Windows.Networking.Vpn) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpncredentialtype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpncredentialtype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpncredentialtype.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2018-08-23 00:09
Thanks for the question, @jjherman94. I'll make enquiries and get back to you with any info I can find out. ~Steve

**Comment by jjherman94** [comment] 2018-08-23 15:13
Thank you. And when I do create and try to connect to a dummy VPN connection with the smart card option selected it does ask me to insert a smart card.
![20180822_152527_hololens](https://user-images.githubusercontent.com/5394456/44534313-b2452480-a6b4-11e8-861b-7381c0927fe7.jpg)

**Comment by jjherman94** [comment] 2018-08-24 19:17
I guess also what about Microsoft's virtual smart cards? The HoloLens seems to meet the hardware and software requirements.
https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview

**Comment by stevewhims** [comment] 2018-08-24 19:36
Hi, @jjherman94, in terms of supporting the HoloLens product, I'm afraid there's little we can offer here. My contacts and myself create and document Windows APIs. We don’t know whether smart cards are supported on HoloLens, nor what kind of smart cards (if any). On the Desktop, smart card selection indicates EAP-TLS authentication, which includes smart card. In terms of next steps for you, the [Windows developer feedback site](https://wpdev.uservoice.com) is the right place to file a product bug. For issues, questions such as this, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a product bug or something else. For problems/errors/omissions with the actual documentation about Windows APIs, this is the right forum to raise those. Thanks again for the feedback and for asking this question. I do regret the inconvenience. ~Steve

**Comment by stevewhims** [comment] 2018-09-14 01:31
@jjherman94, I'll go ahead and close this issue now since it's been a while. ~Steve

**Closed as completed by stevewhims** 2018-09-14 01:31 UTC
