### ISSUE TITLE
Issue in values returned by Battery.GetReport()

### ISSUE THREAD

**Issue by contactgc** [MicrosoftDocs/winrt-api#2456] opened 2024-02-19 13:44 UTC
Hello,

We tried this method to get the battery on a hololens 2 but the values returned are not consistent:

```
#if WINDOWS_UWP
using Windows.Devices.Power;
#endif
    ...
#if WINDOWS_UWP    
        var aggBattery = Battery.AggregateBattery; 
        var report = aggBattery.GetReport();

        Debug.Log("Battery Report: DeviceId - " +aggBattery.DeviceId.ToString());
        Debug.Log("Battery Report: Status - " + report.Status.ToString());
        Debug.Log("Battery Report: FullCharge - " + report.FullChargeCapacityInMilliwattHours.ToString());
        Debug.Log("Battery Report: Remaining - " + report.RemainingCapacityInMilliwattHours.ToString());
        Debug.Log("Battery Report: Charge Rate - " + report.ChargeRateInMilliwatts.ToString());
        Debug.Log("Battery Report: Design Capacity - " + report.DesignCapacityInMilliwattHours.ToString());
#endif
```

```
Battery Report: DeviceId - AggregateBattery
Battery Report: Status - Discharging
Battery Report: FullCharge - 4481
Battery Report: Remaining - 3305
Battery Report: Charge Rate - -6751
Battery Report: Design Capacity - 4400
```

The headset was ~70% charged, which was correct from the point of view of FullCharge and Remaining, but the drain rate seems far too high. Remaining autonomy would be 0.48 hour with the battery at 70% (when discharging, RemainingCapacityInMilliwattHours / Abs(ChargeRateInMilliwatts) = remainingTimeInHours). The autnotnomie is actually much higher (between 2h and 2h30).

In this post https://forums.hololens.com/discussion/3133/is-there-a-way-to-get-the-battery-level-from-the-hololens-through-unity, the given values were:
```
Battery Report: DeviceId - AggregateBattery
Battery Report: Status - Discharging
Battery Report: FullCharge - 16710
Battery Report: Remaining - 15664
Battery Report: Charge Rate - -3409
Battery Report: Design Capacity - 16500
```

Both results are from Hololens 2, but capacities are different. 16500 looks like the capacity in mAh, while 4400 looks like the capacity in mWh (i guess). But Charge rate looks to be still in mAh in both.

Is there a unit issue in the values returned by Battery.GetReport() ?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51f9a4e6-fd9e-dda5-17a0-a368078e4966
* Version Independent ID: 043e431f-cad6-9a0e-3e5b-983898253112
* Content: [BatteryReport Class (Windows.Devices.Power) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.devices.power.batteryreport?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.Power/BatteryReport.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Power/BatteryReport.xml)
* Service: **uwp**
* Sub-service: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2024-02-20 20:43
Hi, and thanks for filing this issue. The feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

But this particular issue doesn't feel like it's saying that something needs changing in the docs.

For questions (or requests for help) regarding a specific scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no action to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2024-02-20 20:43 UTC
Labels: Pri2, uwp/svc, winrt-reference/subsvc
