### ISSUE TITLE
Links not functioning

### ISSUE THREAD

**Issue by BenWhite27** [MicrosoftDocs/winrt-api#858] opened 2019-01-13 12:46 UTC
The "Canvas.ZIndex" links are 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42d6cbf5-08bb-5463-ad3e-32ef6f368176
* Version Independent ID: ba7a1bfc-1489-6e3f-415f-9ecce91422ec
* Content: [Canvas.ZIndexProperty Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.canvas.zindexproperty)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment] 2019-04-18 17:28
Duplicate of #736

**Closed as completed by jevansaks** 2019-04-18 17:28 UTC
