### ISSUE TITLE
No documented way to register for a ConnectionStatusChanged event before one connects

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/winrt-api#1043] opened 2019-04-21 23:20 UTC
I do not know if this is due to missing documentation or poor API design. In order to register for a connection status changed event you have to obtain the BluetoothLEDevice object; but the catch 22 is that you cannot obtain the BluetoothLEDevice without initiating an asynchronous connection attempt. By the time one gets the BluetoothLEDevice object, the event has passed. I have never seen a Bluetooth API where one could not register for all callbacks that could be potentially called BEFORE a connection was even attempted. There is clearly something missing here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a05df98-9097-754c-4f8e-0a3b277ed5a7
* Version Independent ID: 405cca73-bc63-ce19-69ec-8a460156857a
* Content: [BluetoothLEDevice Class (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment] 2019-11-05 00:06
Hi, @brianreinhold. Sorry for the long delay in responding.

I don't have any additional content for your scenario, over and above what's in the documentation. So it might be worth your pursuing this as a question about the product, rather than as feedback about the documentation. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Sorry that I couldn't be of more immediate help here.
-Steve

**Comment by stevewhims** [comment] 2019-12-03 00:35
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-12-03 00:35 UTC
Labels: product-question

**Comment by brianreinhold** [comment] 2019-12-03 12:00
Doesn't matter anyways, there is a bug that still has not been addressed that doesn't even allow one to get this far. Until that bug is fixed there we cannot go forward with MS Bluetooth Low energy; it simply does not work when using the advertiser (at least in C++ WinRT)
