### ISSUE TITLE
Connection to TunTap Interface

### ISSUE THREAD

**Issue by marcusrunge** [MicrosoftDocs/winrt-api#1114] opened 2019-06-02 13:15 UTC
Unfortunately due to poor documentation and complete absence of working examples I Need to ask whether it is possible to establish a VPN Connection to something called in the Linux world Tun/Tap Interface used for OpenVPN? I have been Burning Hours and nerves in the past weeks to get something simple to work (experimental "ToyVpn"). Everything beyond authentication Fails at Nothing received timeout. See this: https://github.com/marcusrunge/ToyVpn and this: https://android.googlesource.com/platform/development/+/master/samples/ToyVpn/server/linux
Microsoft, you Need to provide proper documentation and examples on this api, or you can remove it, because nobody is able to get it working!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a47d2c-61a3-01b3-d0dc-73a4b7d5117f
* Version Independent ID: 4c713fb3-f086-5319-cf44-33346a7a14b7
* Content: [Windows.Networking.Vpn Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-07-02 22:03
Adding @PeterSmithRedmond, for advice. Is this an issue we can redress via documentation; or is it a support matter?

@marcusrunge, my apologies for not responding sooner; this one fell through the cracks.

~Steve

**Comment by marcusrunge** [comment] 2019-07-03 12:43
There is a well documented example with Server and Client necessary. There is no word About which vpn types are supported. If tun/tap is not supported, tun/tap should be added as a vpn type to implement own protocols like openvpn. All attempts trying to establish a stable tun/tap Connection failed because Nothing arrived at the "ToyVPN Server". As I said, from developers perspective this interface Can currently not seriously considered. Thats why I advised my Company to stop all attempts using this interface and do it the old way...

**Comment by stevewhims** [comment] 2019-11-04 23:41
UPDATE: I've sent a reminder to the feature team, to see whether they have info about the question here. ~Steve

**Comment by PeterSmithRedmond** [comment] 2019-11-06 00:38
PM of the VPN Client team here. We're working to create a publicly-usable sample now and are working to improve our documentation.

**Comment by dovholuknf** [comment] 2019-11-06 14:16
Marcusrunge and I agree. Adding a comment because we need this information too. I'm also willing to work with MS on how to make this API better - if MS is interested...

**Comment by dovholuknf** [comment] 2020-02-12 15:30
@PeterSmithRedmond - any updates or opportunities for the community (me?) to engage/help out?

**Comment by dovholuknf** [comment] 2020-04-01 15:57
@PeterSmithRedmond with the surge in VPN related tech - any chance to get an update here? Please? :) 
thanks!

**Comment by stevewhims** [comment] 2020-06-03 01:21
Just a heads up that I'm closing this GitHub issue since there's no specific update needed to this topic at this time.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Thanks!
Steve

**Closed as completed by stevewhims** 2020-06-03 01:21 UTC
Labels: product-question, winrt-reference/tech, uwp/prod

**Comment by dovholuknf** [comment] 2020-06-03 01:28
That's too bad. The update needed is better doc for the vpn namespace and a working sample
