### ISSUE TITLE
Alternative way to get radios on Desktop

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/winrt-api#338] opened 2018-05-02 11:26 UTC
Please, document alternative way to get radios for the Desktop app compiled for x86 and running on x64. See also https://github.com/MicrosoftDocs/winrt-api/pull/235

Maybe some WMI query and `Radio.FromIdAsync`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f21cd4-880d-b4d3-19ce-3214bd577861
* Version Independent ID: f29e26e0-5a3f-5fc7-e5a8-87d11465c50d
* Content: [Radio.GetRadiosAsync Method (Windows.Devices.Radios) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio.getradiosasync#Windows_Devices_Radios_Radio_GetRadiosAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2019-10-22 01:20
Hi, @xmedeko. Thanks for filing this issue, and my apologies for the long delay in responding.

The question first seems to be: *is* there an alternative way, for a use case with those particular constraints.

It might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by xmedeko** [comment] 2019-10-22 06:34
Hi @stevewhims, thanks for the reply. I hope there **is** some way to get all radios for all architectures, otherwise it limits the use of this functionality. If this question should be directed to another Microsoft department, please do it.

Finally, I have decided to do a WMI query and `Radio.FromIdAsync`, which has somewhat worked (with all troubles of WMI queries have), but I am not sure if that is correct for all use cases.

Anyway, I no longer work on the Win BLE product. My last knowledge about the problem is that the product team planned migrate to Unity 3D and try the commercial btframework.com, but do not know the status of the product now. So, feel free to close this issue.

**Comment by stevewhims** [comment] 2019-10-22 19:07
Thanks, @xmedeko. I'll go ahead and close this, then, since I'm unable (with current info we have) to resolve it by updating the documentation.

Thanks!
Steve

**Closed as completed by stevewhims** 2019-10-22 19:07 UTC
Labels: product-question
