### ISSUE TITLE
Inconsistent implementation

### ISSUE THREAD

**Issue by AnFunctionArray** [MicrosoftDocs/winrt-api#1177] opened 2019-07-20 16:00 UTC
My program sometimes hangs waiting for DisconnectProfileAsync and ConnectProfileWithPasswordCredentialAsync. 

However when using Internal::RasMediaManager with the Immersive Control Panel everything works all the time. 

Why not make both share the same code base.

Additionally when I create an profile with RequireVpnClientAppUI enabled and then edit this same profile with the immersive control panel it gets converted to Dial-Up connection and is no longer accessible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a47d2c-61a3-01b3-d0dc-73a4b7d5117f
* Version Independent ID: 4c713fb3-f086-5319-cf44-33346a7a14b7
* Content: [Windows.Networking.Vpn Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-07-23 00:30
Hi, @bsld, thanks for reaching out with this issue. For problems/errors/omissions *with the actual documentation* about how Windows APIs work, this feedback mechanism (**Send feedback about** \> **This page**) takes you to the right place to raise those.

But this particular issue doesn't look like something that I can fix by making a change to the docs. This feedback mechanism is to draw attention to issues that a writer can fix just by changing the documentation. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all the developer support resources.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

Thanks!
Steve

**Closed as completed by stevewhims** 2019-07-23 00:30 UTC
