### ISSUE TITLE
Example code?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#1472] opened 2020-02-27 20:31 UTC
Could we see example code in cpp/winrt showing a MidiOutput port created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e2981-84f1-8adb-d8e8-e7fdbbd0da66
* Version Independent ID: 348af48f-3897-76c4-1165-5fca3599be29
* Content: [MidiOutPort.FromIdAsync(String) Method (Windows.Devices.Midi) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi.midioutport.fromidasync#Windows_Devices_Midi_MidiOutPort_FromIdAsync_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.midioutport.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.midioutport.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-02-27 22:52
Hi, @jevansAN, I have an update published with a code example (so I'm updating this comment, as I mentioned).

-Steve

**Comment by jevansAN** [comment] 2020-02-27 23:24
Steve, it’s wonderful to see an answer like that. Very helpful.
Unfortunately it doesn’t solve my particular problem, which I put into a Community posting, so far with no answer.
I plugged in your below code as as a class method in my MidiHandler and it works fine - in one of my two projects.
I have two projects in the same solution, sharing almost all of their code and resources.
They share the MIDIHandler, and what brought me back to questioning this was that one of the two apps does just great in playing Midi, and the other one is silent because the call to create an output port produces a null.
I can find no difference between the way these two projects call the init of the MIDI device, so I was hoping your code would reveal something that would explain why my solution works in one project and not the other. But your code also succeeds in the first project and returns a null port when called by the other program. There are no compile or runtime errors.
I can’t imagine why the port cannot be created in the second program - I wondered if there might be an #include missing, or maybe there is something that needs enabling in the project? The two seem to have the same #includes in their .pch files, and almost exactly the same project settings as near as I can tell. If it was Apple I’d assume I had left some component out of the build.

Thanks, Jeff


On Feb 27, 2020, at 2:52 PM, Steven White <notifications@github.com> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, I have an update in the publishing pipeline. Until that goes live, here's the code I added.

// Opens the default MIDI output device.
winrt::Windows::Foundation::IAsyncOperation<IMidiOutPort> OpenDefaultMidiOut()
{
    IMidiOutPort midiOut{ nullptr };

    winrt::hstring midiOutQueryString{ MidiOutPort::GetDeviceSelector() };
    DeviceInformationCollection midiOutDevices{ co_await DeviceInformation::FindAllAsync(midiOutQueryString) };
    uint32_t selectedMidiDevice{ 0 };

    if (0 == midiOutDevices.Size())
    {
        // No Midi output devices.
        co_return midiOut;
    }
    // If there are > 1 MIDI out devices, pick the first non-integrated one.
    else if (2 <= midiOutDevices.Size())
    {
        for (uint32_t midiDeviceIdx = 0; midiDeviceIdx < midiOutDevices.Size(); midiDeviceIdx++)
        {
            if (false == MidiSynthesizer::IsSynthesizer(midiOutDevices.GetAt(midiDeviceIdx)))
            {
                selectedMidiDevice = midiDeviceIdx;
                break;
            }
        }
    }

    midiOut = co_await MidiOutPort::FromIdAsync(midiOutDevices.GetAt(selectedMidiDevice).Id());

    co_return midiOut;
}
I'll update this comment when the code is live.

-Steve

**Comment by jevansAN** [comment] 2020-02-28 18:11
p.s. There is one possibly telling clue that I should have mentioned - maybe you are the one who will know what it points to:
Of course one can’t quite step through those async methods, but I noticed that when trying to do so in the app that cannot get an output port even when using your below code the output window at some point puts up an error: 
WinRT originate error - 0x887A0004 : 'The specified device interface or feature level is not supported on this system.’.
The target and minimum system settings are the same as on the functioning project, so this is a mystery. I wonder if it could relate somehow to my earlier attempt to update cppwinrt - that produced lots of link errors, so I uninstalled that and returned to the older version 2.0.1990620.2. But if that’s the trouble I should think both of the solution’s projects would have  been affected.

Thanks, Jeff


Steve, it’s wonderful to see an answer like that. Very helpful.
Unfortunately it doesn’t solve my particular problem, which I put into a Community posting, so far with no answer.
I plugged in your below code as as a class method in my MidiHandler and it works fine - in one of my two projects.
I have two projects in the same solution, sharing almost all of their code and resources.
They share the MIDIHandler, and what brought me back to questioning this was that one of the two apps does just great in playing Midi, and the other one is silent because the call to create an output port produces a null.
I can find no difference between the way these two projects call the init of the MIDI device, so I was hoping your code would reveal something that would explain why my solution works in one project and not the other. But your code also succeeds in the first project and returns a null port when called by the other program. There are no compile or runtime errors.
I can’t imagine why the port cannot be created in the second program - I wondered if there might be an #include missing, or maybe there is something that needs enabling in the project? The two seem to have the same #includes in their .pch files, and almost exactly the same project settings as near as I can tell. If it was Apple I’d assume I had left some component out of the build.

Thanks, Jeff


On Feb 27, 2020, at 2:52 PM, Steven White <notifications@github.com <mailto:notifications@github.com>> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, I have an update in the publishing pipeline. Until that goes live, here's the code I added.

// Opens the default MIDI output device.
winrt::Windows::Foundation::IAsyncOperation<IMidiOutPort> OpenDefaultMidiOut()
{
    IMidiOutPort midiOut{ nullptr };

    winrt::hstring midiOutQueryString{ MidiOutPort::GetDeviceSelector() };
    DeviceInformationCollection midiOutDevices{ co_await DeviceInformation::FindAllAsync(midiOutQueryString) };
    uint32_t selectedMidiDevice{ 0 };

    if (0 == midiOutDevices.Size())
    {
        // No Midi output devices.
        co_return midiOut;
    }
    // If there are > 1 MIDI out devices, pick the first non-integrated one.
    else if (2 <= midiOutDevices.Size())
    {
        for (uint32_t midiDeviceIdx = 0; midiDeviceIdx < midiOutDevices.Size(); midiDeviceIdx++)
        {
            if (false == MidiSynthesizer::IsSynthesizer(midiOutDevices.GetAt(midiDeviceIdx)))
            {
                selectedMidiDevice = midiDeviceIdx;
                break;
            }
        }
    }

    midiOut = co_await MidiOutPort::FromIdAsync(midiOutDevices.GetAt(selectedMidiDevice).Id());

    co_return midiOut;
}
I'll update this comment when the code is live.

-Steve

**Comment by jevansAN** [comment] 2020-02-28 19:17
p.p.s. not a good clue after all - I see I can find that error in the output of the functioning project as well.
------

p.s. There is one possibly telling clue that I should have mentioned - maybe you are the one who will know what it points to:
Of course one can’t quite step through those async methods, but I noticed that when trying to do so in the app that cannot get an output port even when using your below code the output window at some point puts up an error: 
WinRT originate error - 0x887A0004 : 'The specified device interface or feature level is not supported on this system.’.
The target and minimum system settings are the same as on the functioning project, so this is a mystery. I wonder if it could relate somehow to my earlier attempt to update cppwinrt - that produced lots of link errors, so I uninstalled that and returned to the older version 2.0.1990620.2. But if that’s the trouble I should think both of the solution’s projects would have  been affected.

Thanks, Jeff


Steve, it’s wonderful to see an answer like that. Very helpful.
Unfortunately it doesn’t solve my particular problem, which I put into a Community posting, so far with no answer.
I plugged in your below code as as a class method in my MidiHandler and it works fine - in one of my two projects.
I have two projects in the same solution, sharing almost all of their code and resources.
They share the MIDIHandler, and what brought me back to questioning this was that one of the two apps does just great in playing Midi, and the other one is silent because the call to create an output port produces a null.
I can find no difference between the way these two projects call the init of the MIDI device, so I was hoping your code would reveal something that would explain why my solution works in one project and not the other. But your code also succeeds in the first project and returns a null port when called by the other program. There are no compile or runtime errors.
I can’t imagine why the port cannot be created in the second program - I wondered if there might be an #include missing, or maybe there is something that needs enabling in the project? The two seem to have the same #includes in their .pch files, and almost exactly the same project settings as near as I can tell. If it was Apple I’d assume I had left some component out of the build.

Thanks, Jeff


On Feb 27, 2020, at 2:52 PM, Steven White <notifications@github.com <mailto:notifications@github.com>> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, I have an update in the publishing pipeline. Until that goes live, here's the code I added.

// Opens the default MIDI output device.
winrt::Windows::Foundation::IAsyncOperation<IMidiOutPort> OpenDefaultMidiOut()
{
    IMidiOutPort midiOut{ nullptr };

    winrt::hstring midiOutQueryString{ MidiOutPort::GetDeviceSelector() };
    DeviceInformationCollection midiOutDevices{ co_await DeviceInformation::FindAllAsync(midiOutQueryString) };
    uint32_t selectedMidiDevice{ 0 };

    if (0 == midiOutDevices.Size())
    {
        // No Midi output devices.
        co_return midiOut;
    }
    // If there are > 1 MIDI out devices, pick the first non-integrated one.
    else if (2 <= midiOutDevices.Size())
    {
        for (uint32_t midiDeviceIdx = 0; midiDeviceIdx < midiOutDevices.Size(); midiDeviceIdx++)
        {
            if (false == MidiSynthesizer::IsSynthesizer(midiOutDevices.GetAt(midiDeviceIdx)))
            {
                selectedMidiDevice = midiDeviceIdx;
                break;
            }
        }
    }

    midiOut = co_await MidiOutPort::FromIdAsync(midiOutDevices.GetAt(selectedMidiDevice).Id());

    co_return midiOut;
}
I'll update this comment when the code is live.

-Steve

**Comment by jevansAN** [comment] 2020-03-02 17:52
Steve,

	Recalling that I can’t get a MIDI output port in one of these projects though using the same code in both (and yours!), I have a question you may be able to answer.
	Searching for differences between these two projects with special attention to Devices  I find a curiosity in the external dependencies:

The project that can get a MIDI output port lists

	Windows.Devices.Enumeration.0.h
	Windows.Devices.Enumeration.1.h
	Windows.Devices.Enumeration.2.h
	Windows.Devices.Enumeration.h

The project that receives a null output port lists

	Windows.Devices.Enumeration.0.h
	Windows.Devices.Enumeration.1.h
	Windows.Devices.Enumeration.2.h
	Windows.Devices.Enumeration.h
	Windows.Devices.Enumeration.Pnp.0.h
	Windows.Devices.Enumeration.Pnp.1.h
	Windows.Devices.Enumeration.Pnp.2.h

Since those dependencies are provided by VS I’m not sure it would be safe to remove the Pnp files, and I wonder why this difference would exist in two projects that have the same characteristics except that one was created a year or two ago and the second, failing one more recently. But do you know what is going on here? No compile or run-time errors are produced by your code for obtaining an output port, but in the second case the port returned is null.

	Thanks, Jeff

**Comment by jevansAN** [comment] 2020-03-03 18:52
Steven,

	Don’t want to bug you forever, but you’ve been very helpful in the past and this Midi issue may require input from an insider who knows what’s going on, so I’m trying to boil my problem down to its bare essentials:

I have two cppwinrt projects sharing a Midi handler in a solution.

In the first one, having established that the output device array has an entry, this code, like that in your sample, returns an output port:

		devInfo = m_output_devices.GetAt(0);
		m_midi_out_port = co_await MidiOutPort::FromIdAsync(devInfo.Id());

In the second project, with output devices again containing one device, that same code returns a null port.

The only possibly relevant difference I can find between the two projects is that the second one contains in its external dependencies some references that are not found in the dependencies of the first project, which was created a year or so earlier:

	Windows.Devices.Enumeration.Pnp.0.h
	Windows.Devices.Enumeration.Pnp.1.h
	Windows.Devices.Enumeration.Pnp.2.h

Of course those dependencies are generated by Visual Studio and I don’t know why they are different in the two projects or how they could be changed. But could this difference be related to the failure of FromIdAsync in the second project?

Thanks, Jeff

**Comment by jevansAN** [comment] 2020-03-04 00:23
p.s. Another clue: after turning off optimization I noticed this in the Output window right after trying to connect to an output port:

Natvis C++/WinRT: Could not find metadata for Windows.Foundation.Collections.IVectorView`1<Windows.Devices.Enumeration.DeviceInformation>

This seems to be a cppwinrt thing. Perhaps it would be better to post it at GitHub

Jeff


Steven,

	Don’t want to bug you forever, but you’ve been very helpful in the past and this Midi issue may require input from an insider who knows what’s going on, so I’m trying to boil my problem down to its bare essentials:

I have two cppwinrt projects sharing a Midi handler in a solution.

In the first one, having established that the output device array has an entry, this code, like that in your sample, returns an output port:

		devInfo = m_output_devices.GetAt(0);
		m_midi_out_port = co_await MidiOutPort::FromIdAsync(devInfo.Id());

In the second project, with output devices again containing one device, that same code returns a null port.

The only possibly relevant difference I can find between the two projects is that the second one contains in its external dependencies some references that are not found in the dependencies of the first project, which was created a year or so earlier:

	Windows.Devices.Enumeration.Pnp.0.h
	Windows.Devices.Enumeration.Pnp.1.h
	Windows.Devices.Enumeration.Pnp.2.h

Of course those dependencies are generated by Visual Studio and I don’t know why they are different in the two projects or how they could be changed. But could this difference be related to the failure of FromIdAsync in the second project?

Thanks, Jeff

**Comment by stevewhims** [comment] 2020-04-02 02:50
Hi, Jeff (@jevansAN), and sorry for my delay in responding!

My own contribution here is limited to documenting the normal functioning of the platform APIs, as well as how we recommend using them. I'm not able to provide the kind of product support you'll get from other channels.

This feedback channel (**Send feedback about** \> **This page**) is for feedback about the documentation itself, so pointing out that there's no code example is the kind of thing we're looking for here.

For feedback about the design and performance of the product itself, and/or support with your particular applications, you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you find that info is missing from the docs, or incorrect in the docs, then please come back and let us know.

I'll go ahead and close this issue now, since there's no action I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve

**Closed as completed by stevewhims** 2020-04-02 02:50 UTC
Labels: doc-enhancement, winrt-reference/tech, uwp/prod

**Comment by jevansAN** [comment] 2020-04-02 04:08
Steven, thanks much for responding. I do tend to ask in inappropriate places (wherever I see a chance to get someone’s attention). This one I solved in the end and perhaps it could be seen as a documentation issue. Your sample code was excellent, but what I was missing was that I needed to paste into the project file an item group referencing the DLS synth. Without that the code produces no sound when directed to the default internal device. I had actually known that at one point and it finally came back to mind. No idea where I learned it - probably Googling.

Jeff


On Apr 1, 2020, at 7:50 PM, Steven White <notifications@github.com> wrote:


Hi, Jeff (@jevansAN <https://github.com/jevansAN>), and sorry for my delay in responding!

My own contribution here is limited to documenting the normal functioning of the platform APIs, as well as how we recommend using them. I'm not able to provide the kind of product support you'll get from other channels.

This feedback channel (Send feedback about > This page) is for feedback about the documentation itself, so pointing out that there's no code example is the kind of thing we're looking for here.

For feedback about the design and performance of the product itself, and/or support with your particular applications, you can click Send feedback about > This product, and you'll be taken to Microsoft Q&A <https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all> (more info about that below).

Here are all of the developer support resources, for completeness.

Microsoft Q&A <https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all> is the right place to lobby for a change, a feature, or to make a suggestion.
For community assistance with development questions, there are our forums <https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required>, and StackOverflow <https://stackoverflow.com/questions>.
The Windows developer support <https://developer.microsoft.com/windows/support> site explains other support options.
The Visual Studio developer community <https://developercommunity.visualstudio.com/> is available, and responsive. The former User Voice feature is now there on the Suggest a feature tab, if you want to lobby for a change, a feature, or to make a suggestion.
For developer issues, or suspected product bugs, there's Microsoft Support <https://support.microsoft.com/contactus>; a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
If you find that info is missing from the docs, or incorrect in the docs, then please come back and let us know.

I'll go ahead and close this issue now, since there's no action I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

-Steve
