### ISSUE TITLE
On error, what happens to a download?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1731] opened 2020-07-17 16:28 UTC
The article https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgrounddownloader states that background downloads are persisted unless reattached (and eventually completed). What happens to a download when Attach'ing it fails? Is it disposed? Is it remains, out of the applications reach (and would it then prevent it from starting another download on the same URI)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfbf6f6a-e8a1-1683-f9fc-93054c911c6b
* Version Independent ID: f8466491-c957-a6dd-baca-bf45df1cd4e7
* Content: [DownloadOperation.AttachAsync Method (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.downloadoperation.attachasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.BackgroundTransfer/DownloadOperation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.BackgroundTransfer/DownloadOperation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2020-07-18 00:07
Hi, @avakhrushev, and thanks for filing this issue. I don't have the info to answer this question, so I've notified the feature team (product group) about this issue, and sent them a link to it. In the meantime, be aware of these links in case you want to make use of them.

<DEVELOPER SUPPORT RESOURCES>

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

-Steve

**Comment by PeterSmithRedmond** [comment] 2020-07-18 00:48
The download will persist until attached and completed. but notice that most of the possible errors are either transient (like out of memory) or essentially impossible (like the access denied error) , or only possible based on unlikely programming issues (object disposed or invalid argument). 

I would expect a typical user in the likely cases (out of memory) would exit the app and retry, at which point the attach would work

Note that the access denied can only be gotten if you start a download with a working program, then pause the donwloads, then update the user's app with a new version with reduced capabilities (e.g., you removed the private network capability and the download is from the local private network), and then attempt to attach.

**Comment by avakhrushev** [comment] 2020-07-22 11:57
"Most", "likely", the odds talk. I'd prefer to know how we are to make our apps behave, than to be comforted.
What if say keeping unfinished background downloads is what causes the Out Of Memory in the first place? Sounds like an unrecoverable state.

**Comment by PeterSmithRedmond** [comment] 2020-07-22 18:21
As long as you are attaching to the transfers when your app runs (e.g., at app start), then you are doing enough to keep the transfers running correctly. There are no extra steps needed.

In your hypothetical -- what if it's background transfer that causing the out of memory? -- we've never had a background transfer issue reported to us for this.

**Comment by avakhrushev** [comment] 2020-07-22 19:00
But the exceptions thrown are not hypothetical. Perhaps so should be the handling procedures.

Anyway, I don't see the point in dragging this discussion further. The feedback is given, I think there is a room for improving the articles, _possibly_ the product itself. The rest is not up to me.

**Comment by stevewhims** [comment] 2020-08-04 22:31
Hi, @avakhrushev. Thanks for your feedback. I'll go ahead and close this issue now, and I'll ping our SME to see whether there are any necessary changes needed to the topic.

Thanks!
Steve

**Closed as completed by stevewhims** 2020-08-04 22:31 UTC
Labels: product-question, winrt-reference/tech, uwp/prod, Pri2
