### ISSUE TITLE
Do WinRT C++ apps receive input from an Xbox One Controller while the app is not in focus?

### ISSUE THREAD

**Issue by OOPMan** [MicrosoftDocs/winrt-api#1011] opened 2019-04-05 19:41 UTC
Do WinRT C++ apps receive input from an Xbox One Controller while the app is not in focus?

**Comment by ginami** [comment] 2019-04-05 20:48
Hi @OOPMan --thank you for your comment. Can you tell me which page in our docs you'd expect to find this information? This will help me get your question to the correct author and help us add the answer to the appropriate doc. Thank you!

**Comment by OOPMan** [comment] 2019-04-06 16:26
@ginami The https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input#remarks page states that `UWP apps cannot receive input from an Xbox One Controller while the app is not in focus.` with no explanation as to whether this affects Win32 applications using WinRT to access the API (It does) and no real explanation as to why...

**Comment by stevewhims** [comment] 2019-10-22 02:47
Hi, @OOPMan. Thanks for filing this issue, and my apologies for the long delay in responding.

I don't have any extra info over and above what's in the topic (the info about UWP apps, specifically). I understand that you're asking *not* about UWP apps, but about a Win32 C++ application, that happens to call this WinRT API.

It might be worth your pursuing this as a question about the product, rather than as feedback about the documentation (since there's nothing that I can action, as things stand). You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Thanks!
Steve

**Comment by stevewhims** [comment] 2019-11-04 23:59
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2019-11-04 23:59 UTC
Labels: product-question
