### ISSUE TITLE
Append should be Add

### ISSUE THREAD

**Issue by cborrowman** [MicrosoftDocs/winrt-api#2301] opened 2022-11-18 18:36 UTC
Testing with an azure function, Append produced compilation error for line:
                client.DefaultRequestHeaders.Append("X-Authorization", vueApiAuthToken);

2022-11-18T18:34:35Z   [Error]   Function compilation error
2022-11-18T18:34:35Z   [Error]   run.csx(62,46): error CS1501: No overload for method 'Append' takes 2 arguments

The following compiles and works:
                client.DefaultRequestHeaders.Add("X-Authorization", vueApiAuthToken);

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef232b2-7366-f807-4e7a-a343c3e33087
* Version Independent ID: 425d4895-5a42-4a83-a911-f40174341e55
* Content: [HttpRequestHeaderCollection.Append(String, String) Method (Windows.Web.Http.Headers) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.web.http.headers.httprequestheadercollection.append?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Web.Http.Headers/HttpRequestHeaderCollection.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web.Http.Headers/HttpRequestHeaderCollection.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-11-18 21:39
Hi, @cborrowman, and thanks for filing this issue.

I can confirm that the HttpRequestHeaderCollection.Append(String, String) method does exist (and can be called from a UWP app, for example). If you're using a .NET language (such as C#), then the Add method *also* exists (by virtue of HttpRequestHeaderCollection implementing the IDictionary<TKey,TValue> interface). So both those methods do exist, and are both documented.

I can't account for why Azure Functions isn't finding Append. Perhaps that's due to the language projection you're using (perhaps JavaScript). But it's good that you can work around that by using Add.

I'll close the issue since there are no updates necessary to the docs.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-11-18 21:39 UTC
Labels: winrt-reference/tech, uwp/prod, Pri2
