### ISSUE TITLE
Documentation Clarification Request: IAsyncOperation<TResult> Completed race condition?

### ISSUE THREAD

**Issue by charlesnicholson** [MicrosoftDocs/winrt-api#2455] opened 2024-02-15 23:05 UTC
Hello WinRT team!

First off, I want to say that the C++ WinRT interface to the UWP stuff is very natural and easy to use. Thanks for all of your work on it; it's very natural and pleasant to write C++20 code that uses the new APIs.

I'm working with the BluetoothLE components of UWP in WinRT C++20. Coroutines don't work in the context I'm working in, so I'm using the IAsyncOperation "Completed" property to attach a method to be called upon completion.

I'm curious what machinery prevents the race condition where the IAsyncOperation completes between when the asynchronous function is invoked, and when I attach a method to the Completed property. My assumption is that there are provisions for this that I'm having trouble finding, so I'm assuming this is a documentation (or dumb user) issue. :)

For example, this image is from https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events#delegate-types-for-asynchronous-actions-and-operations

![Screenshot 2024-02-15 175543](https://github.com/MicrosoftDocs/winrt-api/assets/3010295/fea7db01-6006-4de1-8748-5a266b2d2334)

In the above example, if the operation represented by `async_op_with_progress` completes before the Completed property is set with the lambda, does the lambda ever get called? If it doesn't, what pattern should be used to safely detect this race scenario in a heavily multi-threaded environment?

(The above example is not related to the BluetoothLE UWP API but behaves similarly and is possibly even more prone to races: Some of the APIs like `GattCharacteristic.WriteValueAsync` simply queue up data for transmission and complete quickly, without waiting for any network activity. It's easy to imagine Windows choosing to schedule the thread that enqueues the data before even returning to my thread, which would complete the operation before I've had a chance to set a Complete handler!)

Thanks in advance for reading.

**Comment by stevewhims** [comment] 2024-02-22 21:55
Hi, @charlesnicholson, and thanks for filing this issue.

> Hello, WinRT team!

Just for awareness, the feedback channel you're using here (**Submit and view feedback for** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete. So issues filed this way don't go to "the Windows Runtime team". That is, not to the team responsible for designing and implementing WinRT APIs. And they don't go to "the C++/WinRT team". That is, not to the team responsible for designing and implementing the WinRT language projection known as C++/WinRT. Instead, they go to folks who write/edit/publish documentation covering what they know about the aforementioned things; mostly based on info they get from the aforementioned folks. :)

Here, the question seems to be "Assuming there *is* a race condition in this situation, then how does the platform handle that and/or how should the developer handle it." So any race condition is currently hypothetical (although I can very much sympathize with your reasoning that one might exist). So my feeling is that this issue is a little more in the realm of a product question than an issue with the documentation (although, I might be wrong).

Anyway, I'd recommend clicking **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below). I imagine you'll be able to copy-paste the markdown of the question.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since there's no immediate action that I can take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2024-02-22 21:55 UTC
Labels: Pri3

**Comment by charlesnicholson** [comment] 2024-02-22 22:11
Hey @stevewhims - thanks for the response! That's the trouble with undocumented behavior; it leaves a lot to the imagination :)

I posted my question here https://stackoverflow.com/questions/78007860/iasyncoperation-completed-handler-race-conditions and @oldnewthing chimed in to confirm that there's no race condition and that it's simply a missing explanation in the docs. He said he'd make a note to improve the docs but I'm assuming that since this ticket has had no activity, that it's being tracked elsewhere.

So perhaps this turned out to be the right place to file the request, despite my organizational ignorance?

**Comment by stevewhims** [comment] 2024-02-22 22:15
Cool, it sounds like @oldnewthing is tracking this already. I *could* go in now and just write "There's no race condition in the example above" (for the sake of expediency), but I think it'd be better to let @oldnewthing explain it better than I could. :)

-Steve
