### ISSUE TITLE
It's difficult for app vendor to understand how to use above interface

### ISSUE THREAD

**Issue by ethanfan1p** [MicrosoftDocs/winrt-api#936] opened 2019-02-20 10:37 UTC
Recommend demonstrate with sample codes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a66cc6-f5db-2425-e50d-07072c09994a
* Version Independent ID: ba2e58ed-ce3e-1c21-78db-3ab29f097777
* Content: [VideoDeviceController.GetDevicePropertyByExtendedId(Byte\[\], IReference&lt;UInt32&gt;) Method (Windows.Media.Devices) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.videodevicecontroller.getdevicepropertybyextendedid#Windows_Media_Devices_VideoDeviceController_GetDevicePropertyByExtendedId_System_Byte___Windows_Foundation_IReference_System_UInt32__)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.devices.videodevicecontroller.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.devices.videodevicecontroller.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment] 2019-02-20 17:08
Hello, this API is intended to be used by the developer of the driver for a particular video capture device. They pass in the string name of a property and the method returns an object with the value for that property. But the actual property names and values are determined by the hardware vendor. Are you a are hardware vendor having difficulty obtaining your proprietary property values?

**Comment by kennethtang4** [comment] 2020-02-16 06:23
I am a hardware vendor that has developed a video camera and had a very hard time finding how this works. In fact, I still yet to find out how does all this work.

I have already been reading:
UVC Extension Unit Code Samples: [https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/uvc-extension-unit-code-samples](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/uvc-extension-unit-code-samples)
Registering KS Proxy Plug-ins: [https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/registering-ks-proxy-plug-ins](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/registering-ks-proxy-plug-ins)
Property Page Plug-in: [https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/property-page-plug-in](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/property-page-plug-in)

And read more than hundreds of pages of other articles but it seems the above are the most relevant ones. The point is, I am unable to find a single document that describes what interface is needed to be implemented for this function to work magically. In the "Sample Application for UVC Extension Units",  it took 5 calls to get the value. So my question is, do we simply implement as the "UVC Extension Unit Code Samples" and everything else will be called behind the scene or are we missing something here in order to make it work? If that is the first case, it would be a lot more helpful to put a reference link and explain that briefly in the description of that function.

**Comment by drewbatgit** [comment] 2020-02-18 17:11
@barrygolden will you take a look at this issue?

**Comment by drewbatgit** [comment] 2020-08-28 17:32
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue.

GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) site is the home for technical questions and answers at Microsoft.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.

**Comment by drewbatgit** [comment] 2021-02-26 19:05
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. I recommend raising this issue with the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

**Closed as completed by drewbatgit** 2021-02-26 19:05 UTC
Labels: doc-bug, uwp/prod, Pri2
