### ISSUE TITLE
HTTP Post File - The certificate authority is invalid or incorrect

### ISSUE THREAD

**Issue by Mt-Perazim** [MicrosoftDocs/winrt-api#2217] opened 2022-05-03 08:39 UTC
I have an ASP.Net 6 Web Api, which I have already been able to access via a Python project and a C++ project (via Curl). The api can also be tested via Postman. Every time doing so I had to ignore that the certification was invalid/untrusted and it worked.

**My Question:**
In WinRT I got the expected error for invalid/untrusted certification, so I looked up what to do and ended up using `IgnorableServerCertificateErrors` from `HttpBaseProtocolFilter`, like you can see at the end of my code. But that did not fix my error. I still get the error:
```
WinRT originate error - 0x80072F0D : 'The certificate authority is invalid or incorrect'.
WinRT originate error - 0x80190190 : 'The response status code does not indicate success: 400 ().'.
```
What am I missing?

**Code:**
```
    void HL2ResearchMode::SendPLY(std::wstring const& pointCloud)
    {
        init_apartment();

        .....

        try
        {
            // Send the POST request.
            winrt::Windows::Foundation::Uri requestUri{ L"https://192.168.178.41:5001/api/meshes/uploadPointCloud" };
            winrt::Windows::Web::Http::Filters::HttpBaseProtocolFilter myFilter;

            auto fu = myFilter.IgnorableServerCertificateErrors();
            fu.Append(ChainValidationResult::Expired);
            fu.Append(ChainValidationResult::Untrusted);
            fu.Append(ChainValidationResult::InvalidName);
            fu.Append(ChainValidationResult::InvalidSignature);
            fu.Append(ChainValidationResult::InvalidCertificateAuthorityPolicy);

            winrt::Windows::Web::Http::HttpClient httpClient(myFilter);
            httpResponseMessage = httpClient.PostAsync(requestUri, postContent).get();
            httpResponseMessage.EnsureSuccessStatusCode();
            httpResponseBody = httpResponseMessage.Content().ReadAsStringAsync().get();
        }
        catch (winrt::hresult_error const& ex)
        {
            httpResponseBody = ex.message();
        }
        std::wcout << httpResponseBody;
    }
```

**Comment by stevewhims** [comment] 2022-05-17 00:57
Hi, @arsi0001, and thanks for filing this issue.

For feedback about missing, incorrect, or incomplete info in a specific topic, you can visit the topic and then **Send feedback about** \> **This page**.

For questions/feedback/support about the platform (Windows and its APIs) or tools, you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

You can use the info you've provided above with that product-feedback channel.

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, since it doesn't look like we're identifying any documentation that's wrong. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Closed as completed by stevewhims** 2022-05-17 00:57 UTC
Labels: Pri3
