### ISSUE TITLE
CreateSimpleScanout returning/throwing Invalid Argument?

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/winrt-api#1942] opened 2021-02-12 23:31 UTC
I'm troubleshooting some crashes related to this code, and it appears that at least some of them (related to a newly-plugged-in headset) are caused by CreateSimpleScanout returning/throwing invalid argument. (I'm using c++/winrt, so check_hresult eventually is calling `throw hresult_invalid_argument(hresult_error::from_abi)` in my just-in-time debugging.)

What situations would lead to this? The rest of the code resembles the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 539aaf14-0e90-4aaa-a392-f542407bc661
* Version Independent ID: 90212887-9d7e-fda4-dc37-e3d2888aab6c
* Content: [DisplayDevice.CreateSimpleScanout(DisplaySource, DisplaySurface, UInt32, UInt32) Method (Windows.Devices.Display.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaydevice.createsimplescanout?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Display.Core/DisplayDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Display.Core/DisplayDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2021-02-12 23:42
Hi, @rpavlik, and thanks for filing this issue. I've reached out to the feature team to see whether we should/can improve the documentation here.

Thanks again!
Steve

**Comment by stevewhims** [comment] 2021-03-12 22:52
UPDATE: I've pinged the thread again, will respond here if/when I have news.

Thanks for your patience.

-Steve

**Comment by rpavlik** [comment] 2021-03-16 20:14
If it helps anyone, I have found that closing and re-trying the sequence of calls that led to this will actually cause it to succeed the second time around. Still not sure why it errored in the first place.

**Comment by stevewhims** [comment] 2021-03-30 20:13
Thanks, @rpavlik! I'll go ahead and close the issue since you have a workaround at present. The feature team are aware of the issue, and they might drop onto the thread and ask some clarifying questions. Many thanks, I'll go ahead and close the issue for now, but you can still leave messages here.

Thanks again!
Steve

**Closed as completed by stevewhims** 2021-03-30 20:13 UTC
Labels: doc-bug, winrt-reference/tech, uwp/prod, Pri1

**Comment by AlexanderBabansky** [comment] 2023-08-18 12:11
Still reproducible. Workaround - call this method twice one by one. First throws exception. Second passes.
Happens after display is physically reconnected, or PC rebooted.
Display assigned as _Special, removed from desktop_.

**OS**: Windows 11 Pro for Workstation
**GPU**: Nvidia GeForce RTX 3090, GeForce GTX 1060
**Driver**: 536.99
**Windows SDK**: 10.0.22000.0

Tested on few PCs, displays, video ports.
