### ISSUE TITLE
Timeout exception when calling ConnctAsync

### ISSUE THREAD

**Issue by dungpt4** [MicrosoftDocs/winrt-api#432] opened 2018-06-26 06:03 UTC
After I call PeerFinder.ConnectAsync(peerinformation), what should the advertiser respond for the seeker to avoid timeout exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d69d8fd-820e-71fa-a6f9-2d9d8e74e01c
* Version Independent ID: d6827bef-8fed-9671-58e3-34ac3a9015ad
* Content: [PeerFinder.ConnectAsync(PeerInformation) Method (Windows.Networking.Proximity) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.proximity.peerfinder.connectasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.proximity.peerfinder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.proximity.peerfinder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment] 2018-06-26 18:18
Hi, @dungpt4, I'll investigate this; sorry that I don't have an immediate answer for you, but I'll respond back when I get the info. Thanks for your queries. ~Steve

**Comment by stevewhims** [comment] 2018-07-12 18:45
Thanks for raising this issue, @dungpt4, here's some info for you. The PeerWatcher API (and WiFiDirect/WiFiDirectServices APIs) are reliant upon the correct functioning of the peer-to-peer network connection, and upon the Wi-Fi hardware and driver on both devices. While there is no issue that we're aware of in the sample, please note that the API is not designed to give you a detailed breakdown of what exactly failed. The best way that we can support you with an issue like this is either via Microsoft Support (https://support.microsoft.com/contactus/), or via the [the Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). For the Feedback Hub, you'd have some data capture to do (“Devices and Drivers – Wireless Display and Casting”, maybe “Display and Graphics – Wireless Display and Casting” on newer builds), and you would need to collect that on both devices. FYI, the instructions to get all the traces are likely to be needed would be something like this:

1)        Open Feedback Hub on one machine (A) and report a new problem
2)        Enter the details of the issue you are seeing
3)        Select the “Wireless Display and Casting” category under “Devices and Drivers”
4)        Select “Recreate my problem” and start the capture
5)        On the second machine (B), open Feedback Hub and go to “Advanced Diagnostics”
6)        Select the “Wireless Display and Casting” category under “Devices and Drivers”
7)        Start the capture
8)        Start the application that uses the API on both machines and reproduce the issue
9)        Stop the capture on both machines
10)        On the second machine (B), Click on the path to the “Saved Diagnostic Logs” and copy this to the first machine (A) (you may need to ZIP this folder)
11)        On the first machine (A), add the attachment from the second machine (B)
12)        Submit the feedback on the first machine (A)

**Comment by stevewhims** [comment] 2018-08-10 18:55
@dungpt4, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Closed as completed by stevewhims** 2018-08-10 18:55 UTC
