### ISSUE TITLE
MediaPlayer.AudioDeviceType significance

### ISSUE THREAD

**Issue by Shadolio** [MicrosoftDocs/winrt-api#913] opened 2019-02-10 11:26 UTC
What is MediaPlayer.AudioDeviceType used for? Any suggestions or scenarios for when or what this property can be set or used? For example, I thought that it could be set to "Communications" on a Windows Phone or Windows 10 Mobile device, "Console" if this is an Xbox, and I am not sure when would "Multimedia" be used, but it would fit if Windows would run on a device like an Mp3 player. However, these examples assume that the description of this property means by "primary usage of the device" the usage for the user, while I am also thinking if it means "How the App uses this device for, or sees this device as." For example, if I am building a Music App where the user can play long-running playlists of music and songs in the background, I would see this device being primarily used as a "Multimedia" device, however its primary use as the user intends might be different.

Therefore, I would like to see it more clearly explained: What is the significance of changing the value of this property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1b4b54f-2e92-6493-868a-d04d4ab5b103
* Version Independent ID: 4249ba6a-1d3c-e411-fcb6-dd969c7444d6
* Content: [MediaPlayerAudioDeviceType Enum (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayeraudiodevicetype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayeraudiodevicetype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayeraudiodevicetype.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment] 2020-09-25 17:55
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue.

This API was designed to allow the system to optimize for various scenarios. For example, audio ducking behavior in reaction to other sounds being played. That said, I can't find evidence of any specific optimizations that are made based on this value. So, I can't recommend a particular usage scenario for this API, but it's possible that optimizations may be added to the system for particular values in the future.

**Closed as completed by drewbatgit** 2020-09-25 17:55 UTC
Labels: product-question, uwp/prod, Pri2
