### ISSUE TITLE
Is there a way for BLE peripheral to diff from two centrals subscribe notify , and only notify to one of them specified ?（UWP） 

### ISSUE THREAD

**Issue by 13xiaobang** [MicrosoftDocs/winrt-api#2221] opened 2022-05-10 13:29 UTC
In my BLE case, there seems to be a unsolved problem:
I have two centrals **MasterA** and **MasterB** , both of them do subscribe to one peripheral **DeviceC**. I know both subscribe actions will trigger **SubscribedClientsChanged**  event , but the params for **SubscribedClientsChanged** can not figure out which event comes from **MasterA** or **MasterB**, the only thing seems valuable is **GattLocalCharacteristic::SubscribedClients**, but **SubscribedClients** can not thell any clue such as ble address, device name or other things for MasterA/MasterB. Through the SubscribedClientsChanged event, only things I can know is how many Masters do this subscribe, but can not diff one from another. 

When **DeviceC** want to do notify only to MasterA, even I know the API for **DeviceC** only notify to one Master :

 _notifyCharacteristic->NotifyValueAsync(writer->DetachBuffer(),  /* the subscribe client from SubscribedClients*/);_ 

I can not figure out which SubscribedClient I should add into it.

Am I tell the problem clear ? And any solution for it? help....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c372d17b-6fae-ec75-6ce6-f9daa74e9b40
* Version Independent ID: d091be8d-e2e0-3f47-b08d-473a46c4745e
* Content: [GattSubscribedClient Class (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsubscribedclient?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattSubscribedClient.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattSubscribedClient.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2022-05-10 21:17
Hi, @13xiaobang, and thanks for filing this issue. In this case, it's not clear whether the issue is that something's wrong with the documentation (this would be the right channel for that), or whether this is a question about the product or a support issue (which another channel would process). Since it's in a gray area, I'll do two things. 1) I'll recommend that you pursue this as a product question or support issue, and 2) I'll pass this issue Id along to the feature team so that they have the option to respond and/or ask me to add more info to the documentation.

For questions (or requests for help) regarding a specific scenario (which, as I say, is what this sounds like), you can click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

I'll go ahead and close this issue now, given the proposed plan above. But as I say if the feature team want me to, then I'll add more info to the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.

Thanks!
-Steve

**Comment by 13xiaobang** [comment] 2022-05-11 00:24
Thanks,@stevewhims.
I think the problem comes from the design of BLE api, and I have copied it to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all).

**Comment by stevewhims** [comment] 2022-05-11 00:28
Reopening to address info supplied by the feature team.

**Comment by stevewhims** [comment] 2022-05-19 19:30
Hi, @13xiaobang, I've added info about how to achieve your scenario to the bottom of the [Send notifications to subscribed clients](https://docs.microsoft.com/windows/uwp/devices-sensors/gatt-server#send-notifications-to-subscribed-clients) section.

Thanks!
-Steve

**Closed as completed** 2022-05-19 20:59 UTC
Labels: winrt-reference/tech, uwp/prod, Pri3
