### ISSUE TITLE
No one is interested in any examples...

### ISSUE THREAD

**Issue by andifandrich** [MicrosoftDocs/winrt-api#1258] opened 2019-10-08 12:53 UTC
...so why should anybody writing documentation include them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b195d006-dff9-0a63-7008-3f50887c3be9
* Version Independent ID: a2f8a231-97e4-6f69-7100-93e19171ecb5
* Content: [HttpClient.DefaultRequestHeaders Property (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.defaultrequestheaders)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment] 2019-10-08 22:18
Hi, @andifandrich, can you tell me more about your feedback, please? A large number of customers have expressed an interest in code examples, and so we do try to provide a decent volume of code examples across the Windows content sets from Win32 to Windows Runtime. The opening paragraph of this topic takes the reader to code examples.

Please let me know if you're proposing changes to the content, and what those would be. I'll leave this issue open for a while.

Thanks!
~Steve

**Comment by andifandrich** [comment] 2019-10-09 06:22
Hi Steve,
I'd have never thought that anyone is interested in my comment, so I very much appreciate your answer.
We developers are always looking for code samples and see them a s an essential part of documentation. In this case I searched for DefaultRequestHeaders because I wanted to know how to add some. I was very disappointed, because this is nowhere mentioned on the page. I then followed the link to the class documentation of HttpRequestHeaderCollection and there are plenty of examples. I would suggest to just copy them over.
Cheers
Andi

**Comment by stevewhims** [comment] 2019-11-04 23:31
Thanks, @andifandrich. It can be expensive and error-prone to maintain multiple copies of the same content (code or otherwise). So, where possible, I like to keep a single copy of code (in the conceptual content), and link to that from elsewhere. You also found code in a related API ref topic, so that was good. It looks like the links are working as intended here, but I'll bear this thread in mind in future when I'm improving our code, how and where we factor it to, and how we link.

I'll go ahead and close the issue now.

Thanks!
Steve

**Closed as completed by stevewhims** 2019-11-04 23:31 UTC
Labels: doc-enhancement
