### ISSUE TITLE
How to access DeviceInformation Properties

### ISSUE THREAD

**Issue by semireg** [MicrosoftDocs/winrt-api#900] opened 2019-02-02 20:54 UTC
Referencing this documentation:
https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation

Trying to get as much info about USB devices as possible.

```
  onUpdated = (unknown, devUpdate) => {
    const { id, name, kind, properties } = devUpdate;
    const displayName = properties['System.ItemNameDisplay'];
    const gguid = properties['System.Devices.InterfaceClassGuid'];
...
```

both displayName and gguid are undefined. I've tried everything I can think of... :) How do I access a the properties on a DeviceInformation properties (IReadOnlyDictionary)?

This doesn't have much information:
https://github.com/MicrosoftDocs/winrt-api/blob/9f0afc2b220dde46cd2cf6f117135f3b4c7d1cf5/windows.devices.enumeration/deviceinformation_properties.md

A few other questions:
- What is the type of "unknown" in above code snippet?
- When I JSON.stringify or console.log a winrt object I always get "__winRtInstance__". Is there a better way to inspect an object for the class so I can lookup proper documentation?

Thanks!

**Comment by mcleanbyron** [comment] 2019-02-05 19:01
Hi @semireg. The [DeviceInformation.Properties](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.properties) property contains a dictionary of key/value pairs, where the key for a given property can be one of many types of strings as described in [Device information properties](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/device-information-properties).

It doesn't look like the code example you provided is coming directly from our docs. I tried the C# example in the [DeviceInformation](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation) article and confirmed I can successfully retrieve the "System.ItemNameDisplay" property with the following additional code (for example, "Intel(R) Display Audio Mixer 6.1").

```
object name = null;
deviceInterface.Properties.TryGetValue("System.ItemNameDisplay", out name);
if (name != null)
{
     string nameValue = name as string; 
}
```

In your code example, it appears that you are defining a handler for the [DeviceWatcher.Updated](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher.updated) event. Therefore, the "unknown" parameter is a DeviceWatcher object, as per the event handler definition.

Because it appears you are asking for technical assistance rather than providing direct feedback against the existing docs, I'm closing this issue for now because this docs repo is not a support channel. If you require further technical assistance, you might ask on our [forums](https://social.msdn.microsoft.com/Forums/en-US/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). See [this page](https://developer.microsoft.com/en-us/windows/support) for your support options.

**Closed as completed by mcleanbyron** 2019-02-05 19:01 UTC

**Comment by semireg** [comment] 2019-02-05 19:12
@mcleanbyron, thank you for replying. I am providing feedback. The docs are missing equivalent code in JavaScript. 

How do I access a the properties on a DeviceInformation properties (IReadOnlyDictionary) in JavaScript?

When I try using this code I get "tryGetValue is not a function"
```
properties.tryGetValue('System.ItemNameDisplay')
```

So it seems to be different than C#, but I'm unsure how, because I don't know how to inspect the JavaScript API.

How does one use tryGetValue in JavaScript?

**Comment by mcleanbyron** [comment] 2019-02-05 20:04
Sorry about that - At a glance I didn't realize you had a JavaScript example. I'm not very experienced with JavaScript, but it's possible that TryGetValue is a .NET method and isn't available for this dictionary collection from JavaScript. That said, I was using it as a convenience only. You should still be able to access the property directly from the collection by the key, assuming the property you're querying for exists. 

I just tried out the [Device enumeration and pairing](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DeviceEnumerationAndPairing) example and add the following line of code to the onAdded function in [scenario2_devicewatcher.js](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/DeviceEnumerationAndPairing/js/js/scenario2_devicewatcher.js):

```
var name = deviceInfo.properties['System.ItemNameDisplay'];
```

When I run the code I can successfully retrieve the display name for devices on my computer.

**Comment by semireg** [comment] 2019-02-05 21:01
It's all good. I should have disclosed JS from the start. I just assumed. 😄 

My properties dict is still not responding to any keys, but again, I don't know how to tell that object to show me all of its keys.

I'm creating the watcher with `this.watcher = WindowsDevicesEnumeration.DeviceInformation.createWatcher();` ... maybe the results from this don't have the same (any?) property keys?

I wish there were an easy way to ask the properties object to give me all the known keys. Does that kind of method exist?

**Comment by mcleanbyron** [comment] 2019-02-05 23:55
I'm sorry the code isn't working for you. Have you tried the JavaScript sample I referred to in my previous reply? 

In a .NET language such as C#, you can loop through the [Keys](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlydictionary-2.keys?view=netframework-4.7.2) property of the DeviceInformation.Properties object to see what property keys are in the collection that you retrieve. I'm not sure if or how this can be done from JavaScript, which I'm unfortunately not very familiar with. 

As documented in [Device information properties](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/device-information-properties), these keys correspond to underlying IDs defined by the Windows OS (such as "System.Devices.ContainerId"). These IDs are listed in articles under [this node](https://docs.microsoft.com/windows/desktop/properties/props) in the Windows docs.

**Comment by semireg** [comment] 2019-02-06 16:24
Oh, it's working, it's just that properties object that's opaque. In JavaScript, the way keys are accessed is using `const keys = Object.keys(properties);` However, like I've mentioned above, this only results in `["__winRtInstance__"]` which his a bit useless. That's why I assumed there was an accessor hidden somewhere in the API, but nothing I've tried seems to work the way I'd expect.
