### ISSUE TITLE
wifi/bt enble disable interface can only work in X64

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/winrt-api#457] opened 2018-07-09 16:14 UTC
The issue was created by @luohao1220 from https://github.com/MicrosoftDocs/feedback/issues/490

hi Microsoft，
Currently We use modern Radio interface to enable/disable wifi/bt device, get wifi/bt status, monitor wifi/bt status change.
The Radio interface is work good in X64, but not ok in x86.
Is there any interface can support such function in x86?
thanks
Modern::Windows::Devices::Radios:: Radio
Radio-&gt;SetStateAsync(RadioState::On)
Radio-&gt;SetStateAsync(RadioState::Off)
Radio-&gt;StateChanged(&Callback)
Radio-&gt;State()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6829838-b1e4-5a2d-3ab4-9a3bffa9270f
* Version Independent ID: 14722fc6-d863-cd94-6be3-6e5d63263e2f
* Content: [Radio.SetStateAsync(RadioState) Method (Windows.Devices.Radios) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio.setstateasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by luohao1220** [comment] 2018-07-12 04:53
Hi laurenhughes，
  Can you help to  update this issue？
  Thanks！

**Comment by stevewhims** [comment] 2019-10-22 23:14
Hi, @Powerhelmsman. Thanks for filing this issue, and my apologies for the delay in responding.

I don't have any additional content for your scenario, over and above what's in the documentation. The GetRadiosAsync topic's [Remarks](https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio.getradiosasync#remarks) section mentions an architecture limitation that sounds like what you're experiencing.

This feels not so much like feedback specifically about the documentation, but rather like a question about the product. You got here by clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Windows developer feedback](https://wpdev.uservoice.com) site (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Windows developer feedback](https://wpdev.uservoice.com) site is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know. But I'll go ahead and close this issue for the reasons given.

Thanks!
Steve

**Closed as completed** 2019-10-31 23:07 UTC
Labels: support-request, windows/prod

**Comment by kishorpise** [comment] 2020-05-18 17:08
This does not work at all.  on windows 10 dell laptop 64 bit 18363.836. below is code

var access = await WiFiAdapter.RequestAccessAsync();
            if (access == WiFiAccessStatus.Allowed)
            {
                var radios = await Radio.GetRadiosAsync();
                foreach (var radio in radios)
                {
                    if (radio.Kind == RadioKind.WiFi)
                    {
                        if (! swich)
                        {
                            await radio.SetStateAsync(RadioState.Off);
                        }
